syntax = "proto3";
package auth.v2;

import "auth/v2/permissions.proto";
import "auth/v2/jwt.proto";
import "auth/v2/auth_data.proto";
// import something for time type
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";


service AuthService {
    // Defaults
    option (permission_level_service) = {
        allow_role: PERMISSION_ADMIN
    };
    option (permission_level_service).csrf_token_header = "X-CSRF-Token";
    option (permission_level_service).csrf_token_cookie = "csrf_token";

    rpc GetJWTPublicKey(GetJWTPublicKeyRequest) returns (GetJWTPublicKeyResponse) {
        option (permission_level).allow_role = PERMISSION_API_JWT;
        option idempotency_level = NO_SIDE_EFFECTS;
    }
    rpc RenewJWT(RenewJWTRequest) returns (RenewJWTResponse) {
        option (permission_level).allow_role = PERMISSION_API_JWT;
    }

    rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
        option (permission_level).allow_role = PERMISSION_API_LIST_USERS;
    }

    rpc GetDevToken(GetDevTokenRequest) returns (GetDevTokenResponse) {
        option (permission_level).is_public = true;
    }

    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {
        option (permission_level).allow_role = PERMISSION_ADMIN;
    }
    
    // buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
    // buf:lint:ignore RPC_REQUEST_STANDARD_NAME
    // buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
    rpc UpdateUser(DBUser) returns (DBUser) {
        option (permission_level).allow_role = PERMISSION_ADMIN;
    }

    rpc GetCSRFToken(GetCSRFTokenRequest) returns (GetCSRFTokenResponse) {
        option (permission_level).is_public = true;
    }

    rpc DiscordLogin(google.protobuf.Empty) returns (google.protobuf.Empty) {
        option (permission_level).is_public = true;
        option (permission_level).public_url = "/api/login";
    }

    rpc DiscordCallback(google.protobuf.Empty) returns (google.protobuf.Empty) {
        option (permission_level).is_public = true;
        option (permission_level).public_url = "/api/discord_callback";
    }

    rpc AddPassword(AddPasswordRequest) returns (google.protobuf.Empty) {
        // option (permission_level).enforce_csrf = true; // To be enabled when I actually have a frontend for this
        option (permission_level).is_public = false;
        option (permission_level).allow_role = PERMISSION_ANY_AUTHENTICATED;
    }

    rpc RemovePassword(RemovePasswordRequest) returns (google.protobuf.Empty) {
        // option (permission_level).enforce_csrf = true; // To be enabled when I actually have a frontend for this
        option (permission_level).is_public = false;
        option (permission_level).allow_role = PERMISSION_ANY_AUTHENTICATED;
    }

    rpc PasswordLogin(PasswordLoginRequest) returns (PasswordLoginResponse) {
        option (permission_level).enforce_csrf = true;
        option (permission_level).is_public = true;
    }

    // FRONTEND PAGES
    rpc FrontendIndex(google.protobuf.Empty) returns (google.protobuf.Empty) {
        option (permission_level).is_public = true;
        option (permission_level).is_frontend = true;
        option (permission_level).public_url = "/";
        option (permission_level).public_url = "/index.html";
        option (permission_level).frontend_static_file = "index.html";
    }

    rpc Logout(google.protobuf.Empty) returns (google.protobuf.Empty) {
        option (permission_level).is_public = true;
        option (permission_level).is_frontend = true;
        option (permission_level).public_url = "/logout";
    }
}

message GetJWTPublicKeyRequest {}
message GetJWTPublicKeyResponse {
    string public_key = 1;
}

message RenewJWTRequest {
    string jwt = 1;
    string refresh_token = 2;
}

message RenewJWTResponse {
    string jwt = 1;
    string refresh_token = 2;
    int64 refresh_token_max_age = 3;
    int64 jwt_max_age = 5;
    optional SmallData small_data = 4;
}

message ListUsersRequest {}

message ListUsersResponse {    
    repeated DBUser users = 1;
}

message GetDevTokenRequest {
    string user_id = 1;
    repeated Permission roles = 2;
    optional int64 validity_seconds = 3;
}

message GetDevTokenResponse {
    string jwt = 1;
    string refresh_token = 2;
    google.protobuf.Timestamp refresh_token_expiry = 3;
}

message CreateUserRequest {
    DBUser user = 1;
}

message CreateUserResponse {
    DBUser user = 1;
}

message AddPasswordRequest {
    string password = 1;
    // This user_id can be provided by a user with the PERMISSION_ADMIN role, to change someone else's password. If not provided, the password will be set for the currently authenticated user.
    optional int64 user_id = 2;
}

message RemovePasswordRequest {
    // This user_id can be provided by a user with the PERMISSION_ADMIN role, to remove someone else's password. If not provided, the password will be removed for the currently authenticated user.
    optional int64 user_id = 1;
}

message PasswordLoginRequest {
    string username = 1;
    string password = 2;
    optional bool remember_me = 3;
    optional string redirect_to = 4;
}

message PasswordLoginResponse {
    string redirect_to = 1;
}