import "../utils.just"
set dotenv-load
set fallback
_default: 
    just --list

create-jwt-private-key:
    openssl genpkey -algorithm Ed25519 -out jwt_private_key.pem


CONFIG_DB_PATH := "test_db.sqlite3"
test_private_key := "-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIGSBlJqHrMz/gSJ0QgiEZVVgOmFzSNDT38RS6FPcXgXg
-----END PRIVATE KEY-----"
export HXI2_TLD := "hxi2.fr"
export LOCAL_DEBUG_INSTANCE := "1"
export HXI2_COOKIES_DOMAIN := "localhost"
export CONFIG_ENVIRONMENT := "development"
PORT := "8080"

init: 
    @just _utils-check-program "cargo" 1
    @just _utils-check-program "volta" 0
    cd ../global-frontend-dependencies/ && pnpm install
    pnpm install

[linux,macos]
dev:
    #!/usr/bin/env bash
    if [[ -n "$TMUX" ]]; then
        tmux split-window -d -h "just frontend-dev"
        just test-run
    else
        echo "{{ style("error") }}You must run this command in a tmux session to use the split-window feature{{ NORMAL }}"
        echo "{{ style("error") }}Instead, you should run "just frontend-dev" and "just test-run" in separate terminals{{ NORMAL }}"
    fi

run $HXI2_AUTH_URL="http://localhost:8080" $HXI2_AUTH_ENDPOINT="http://localhost:8080" $CONFIG_JWT_PRIVATE_KEY=test_private_key $CONFIG_DB_PATH=CONFIG_DB_PATH:
    cargo run .

jwt_token_payload := '{"user_id": "42", "roles": [
    "PERMISSION_API_JWT"
]}'

get_jwt:
    curl -s -X POST \
        -H "Content-Type: application/json" \
        -d '{{jwt_token_payload}}' \
        http://localhost:{{PORT}}/auth.v2.AuthService/GetDevToken | jq -r '.jwt'

grpcui:
    grpcui -plaintext \
        -protoset ../generated-proto/hxi2.binpb \
        -H "Authorization: Bearer {{shell('just get_jwt')}}" \
        "0.0.0.0:{{PORT}}"

# get_jwt_public_key:
#     curl -s -X POST \
#         -H "Content-Type: application/json" \
#         -d '{}' \
#         http://localhost:8080/auth.v2.AuthService/GetJWTPublicKey