import "../utils.just"
set dotenv-load
set fallback
_default: 
    just --list

generate-schema:
    cargo test generate_json_schema --features schema-gen -- --nocapture

create-jwt-private-key:
    openssl genpkey -algorithm Ed25519 -out jwt_private_key.pem


CONFIG_DB_PATH := "test_db.sqlite3"
PORT := "8080"
export CONFIG_RUNNING_PORT := PORT

export RUST_LOG := "auth_rs=trace"

jwt_token_payload := '{"user_id": "42", "roles": [
    "PERMISSION_ADMIN"
]}'

init: 
    @just _utils-check-program "cargo" 1
    @just _utils-check-program "volta" 0
    cd ../global-frontend-dependencies/ && pnpm install
    pnpm install

[linux,macos]
dev:
    #!/usr/bin/env bash
    if [[ -n "$TMUX" ]]; then
        tmux split-window -d -h "just frontend-dev"
        just test-run
    else
        echo "{{ style("error") }}You must run this command in a tmux session to use the split-window feature{{ NORMAL }}"
        echo "{{ style("error") }}Instead, you should run "just frontend-dev" and "just test-run" in separate terminals{{ NORMAL }}"
    fi

run:
    cargo run .

get_jwt:
    curl -s -X POST \
        -H "Content-Type: application/json" \
        -d '{{jwt_token_payload}}' \
        http://localhost:{{PORT}}/auth.v2.AuthService/GetDevToken | jq -r '.jwt'

grpcui:
    grpcui -plaintext \
        -protoset ../generated-proto/hxi2.binpb \
        -H "Authorization: Bearer {{shell('just get_jwt')}}" \
        "0.0.0.0:{{PORT}}"

generate-csrf-token:
    openssl rand -base64 32

# get_jwt_public_key:
#     curl -s -X POST \
#         -H "Content-Type: application/json" \
#         -d '{}' \
#         http://localhost:8080/auth.v2.AuthService/GetJWTPublicKey

prepare_sqlx:
    # create a new database file at temp.db, and execute schema.sql in it to create the schema
    sqlite3 temp.db < schema.sql
    DATABASE_URL="sqlite://temp.db" SQLX_OFFLINE=false cargo sqlx prepare --workspace
    rm temp.db