// @generated by protoc-gen-es v2.16.0 with parameter "target=ts"
// @generated from file auth/v2/auth_data.proto (package auth.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v2/auth_data.proto.
 */
export const file_auth_v2_auth_data: GenFile = /*@__PURE__*/
  fileDesc("ChdhdXRoL3YyL2F1dGhfZGF0YS5wcm90bxIHYXV0aC52MiK1AgoGREJVc2VyEgoKAmlkGAEgASgDEhAKCHVzZXJuYW1lGAIgASgJEhIKCmZpcnN0X25hbWUYAyABKAkSFgoJbGFzdF9uYW1lGAQgASgJSACIAQESEgoKZGlzY29yZF9pZBgFIAEoCRI4ChRhY2NvdW50X2NyZWF0ZWRfZGF0ZRgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASOQoVYWNjb3VudF9tb2RpZmllZF9kYXRlGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIRCglwcm9tb3Rpb24YCCABKAUSEwoLcGVybWlzc2lvbnMYCSABKAMSDgoGaXNfYXBpGAogASgIEhIKCmF0dHJpYnV0ZXMYCyABKANCDAoKX2xhc3RfbmFtZSp3CglBdHRyaWJ1dGUSGQoVQVRUUklCVVRFX1VOU1BFQ0lGSUVEEAASEgoOQVRUUklCVVRFX0NVQkUQARISCg5BVFRSSUJVVEVfTVBTSRACEhIKDkFUVFJJQlVURV9QQ1NJEAMSEwoPQVRUUklCVVRFX0JDUFNUEARiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message auth.v2.DBUser
 */
export type DBUser = Message<"auth.v2.DBUser"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string first_name = 3;
   */
  firstName: string;

  /**
   * @generated from field: optional string last_name = 4;
   */
  lastName?: string | undefined;

  /**
   * @generated from field: string discord_id = 5;
   */
  discordId: string;

  /**
   * @generated from field: google.protobuf.Timestamp account_created_date = 6;
   */
  accountCreatedDate?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp account_modified_date = 7;
   */
  accountModifiedDate?: Timestamp | undefined;

  /**
   * @generated from field: int32 promotion = 8;
   */
  promotion: number;

  /**
   * @generated from field: int64 permissions = 9;
   */
  permissions: bigint;

  /**
   * @generated from field: bool is_api = 10;
   */
  isApi: boolean;

  /**
   * @generated from field: int64 attributes = 11;
   */
  attributes: bigint;
};

/**
 * Describes the message auth.v2.DBUser.
 * Use `create(DBUserSchema)` to create a new message.
 */
export const DBUserSchema: GenMessage<DBUser> = /*@__PURE__*/
  messageDesc(file_auth_v2_auth_data, 0);

/**
 * @generated from enum auth.v2.Attribute
 */
export enum Attribute {
  /**
   * @generated from enum value: ATTRIBUTE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ATTRIBUTE_CUBE = 1;
   */
  CUBE = 1,

  /**
   * @generated from enum value: ATTRIBUTE_MPSI = 2;
   */
  MPSI = 2,

  /**
   * @generated from enum value: ATTRIBUTE_PCSI = 3;
   */
  PCSI = 3,

  /**
   * @generated from enum value: ATTRIBUTE_BCPST = 4;
   */
  BCPST = 4,
}

/**
 * Describes the enum auth.v2.Attribute.
 */
export const AttributeSchema: GenEnum<Attribute> = /*@__PURE__*/
  enumDesc(file_auth_v2_auth_data, 0);

