// @generated by protoc-gen-es v2.16.0 with parameter "target=ts"
// @generated from file auth/v2/permissions.proto (package auth.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions, ServiceOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v2/permissions.proto.
 */
export const file_auth_v2_permissions: GenFile = /*@__PURE__*/
  fileDesc("ChlhdXRoL3YyL3Blcm1pc3Npb25zLnByb3RvEgdhdXRoLnYyIp8ECgtQZXJtaXNzaW9ucxInCgphbGxvd19yb2xlGAEgAygOMhMuYXV0aC52Mi5QZXJtaXNzaW9uEhYKCWlzX3B1YmxpYxgCIAEoCEgAiAEBEhIKCnB1YmxpY191cmwYAyADKAkSHgoRY3NyZl90b2tlbl9oZWFkZXIYBCABKAlIAYgBARIeChFjc3JmX3Rva2VuX2Nvb2tpZRgFIAEoCUgCiAEBEkwKFXJlc3BvbnNlX2NvcnNfaGVhZGVycxgGIAMoCzItLmF1dGgudjIuUGVybWlzc2lvbnMuUmVzcG9uc2VDb3JzSGVhZGVyc0VudHJ5EhkKDGVuZm9yY2VfY3NyZhgHIAEoCEgDiAEBEhgKC2lzX2Zyb250ZW5kGAggASgISASIAQESIQoUZnJvbnRlbmRfc3RhdGljX2ZpbGUYCSABKAlIBYgBARIlCgdyZWxhdGVkGAogAygLMhQuYXV0aC52Mi5QZXJtaXNzaW9ucxo6ChhSZXNwb25zZUNvcnNIZWFkZXJzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIMCgpfaXNfcHVibGljQhQKEl9jc3JmX3Rva2VuX2hlYWRlckIUChJfY3NyZl90b2tlbl9jb29raWVCDwoNX2VuZm9yY2VfY3NyZkIOCgxfaXNfZnJvbnRlbmRCFwoVX2Zyb250ZW5kX3N0YXRpY19maWxlKtIBCgpQZXJtaXNzaW9uEiUKIVBFUk1JU1NJT05fUEVSTUlTU0lPTl9VTlNQRUNJRklFRBAAEhQKEFBFUk1JU1NJT05fQURNSU4QARIWChJQRVJNSVNTSU9OX1NUVURFTlQQAhIWChJQRVJNSVNTSU9OX1RFQUNIRVIQAxIWChJQRVJNSVNTSU9OX0FQSV9KV1QQBBIdChlQRVJNSVNTSU9OX0FQSV9MSVNUX1VTRVJTEAUSIAocUEVSTUlTU0lPTl9BTllfQVVUSEVOVElDQVRFRBAGOmQKEHBlcm1pc3Npb25fbGV2ZWwSHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxjxjAMgASgLMhQuYXV0aC52Mi5QZXJtaXNzaW9uc1IPcGVybWlzc2lvbkxldmVsiAEBOnQKGHBlcm1pc3Npb25fbGV2ZWxfc2VydmljZRIfLmdvb2dsZS5wcm90b2J1Zi5TZXJ2aWNlT3B0aW9ucxjyjAMgASgLMhQuYXV0aC52Mi5QZXJtaXNzaW9uc1IWcGVybWlzc2lvbkxldmVsU2VydmljZYgBAWIGcHJvdG8z", [file_google_protobuf_descriptor]);

/**
 * @generated from message auth.v2.Permissions
 */
export type Permissions = Message<"auth.v2.Permissions"> & {
  /**
   * @generated from field: repeated auth.v2.Permission allow_role = 1;
   */
  allowRole: Permission[];

  /**
   * is_public indicates that the method is accessible without any authentication at all.
   *
   * @generated from field: optional bool is_public = 2;
   */
  isPublic?: boolean | undefined;

  /**
   * public_url url indicates the potentially different URL that this method is accessible at. It is used to then regulate permissions automatically.
   *
   * @generated from field: repeated string public_url = 3;
   */
  publicUrl: string[];

  /**
   * @generated from field: optional string csrf_token_header = 4;
   */
  csrfTokenHeader?: string | undefined;

  /**
   * @generated from field: optional string csrf_token_cookie = 5;
   */
  csrfTokenCookie?: string | undefined;

  /**
   * @generated from field: map<string, string> response_cors_headers = 6;
   */
  responseCorsHeaders: { [key: string]: string };

  /**
   * @generated from field: optional bool enforce_csrf = 7;
   */
  enforceCsrf?: boolean | undefined;

  /**
   * @generated from field: optional bool is_frontend = 8;
   */
  isFrontend?: boolean | undefined;

  /**
   * @generated from field: optional string frontend_static_file = 9;
   */
  frontendStaticFile?: string | undefined;

  /**
   * related is a list of routes that are closely related (such as image, css, js); the parser will expand them,
   * inheriting the same permissions as the parent
   *
   * @generated from field: repeated auth.v2.Permissions related = 10;
   */
  related: Permissions[];
};

/**
 * Describes the message auth.v2.Permissions.
 * Use `create(PermissionsSchema)` to create a new message.
 */
export const PermissionsSchema: GenMessage<Permissions> = /*@__PURE__*/
  messageDesc(file_auth_v2_permissions, 0);

/**
 * @generated from enum auth.v2.Permission
 */
export enum Permission {
  /**
   * @generated from enum value: PERMISSION_PERMISSION_UNSPECIFIED = 0;
   */
  PERMISSION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PERMISSION_ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * @generated from enum value: PERMISSION_STUDENT = 2;
   */
  STUDENT = 2,

  /**
   * @generated from enum value: PERMISSION_TEACHER = 3;
   */
  TEACHER = 3,

  /**
   * API Permissions
   *
   * @generated from enum value: PERMISSION_API_JWT = 4;
   */
  API_JWT = 4,

  /**
   * @generated from enum value: PERMISSION_API_LIST_USERS = 5;
   */
  API_LIST_USERS = 5,

  /**
   * MISC
   *
   * @generated from enum value: PERMISSION_ANY_AUTHENTICATED = 6;
   */
  ANY_AUTHENTICATED = 6,
}

/**
 * Describes the enum auth.v2.Permission.
 */
export const PermissionSchema: GenEnum<Permission> = /*@__PURE__*/
  enumDesc(file_auth_v2_permissions, 0);

/**
 * @generated from extension: optional auth.v2.Permissions permission_level = 50801;
 */
export const permission_level: GenExtension<MethodOptions, Permissions> = /*@__PURE__*/
  extDesc(file_auth_v2_permissions, 0);

/**
 * Set the default permissions for all methods in the service, which can be overridden by method-level options
 *
 * @generated from extension: optional auth.v2.Permissions permission_level_service = 50802;
 */
export const permission_level_service: GenExtension<ServiceOptions, Permissions> = /*@__PURE__*/
  extDesc(file_auth_v2_permissions, 1);

