name = "hxi2-static"
compatibility_date = "2025-03-20"

routes = [
    { pattern = "static.hxi2.fr", custom_domain = true },
    { pattern = "hxi2.fr", custom_domain = true },
]
assets = { directory = "./assets", not_found_handling = "none" }
