// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/permissions.proto

#[derive(Clone, Debug, Default)]
pub struct PermissionsView<'a> {
    /// Field 1: `allow_role`
    pub allow_role: ::buffa::RepeatedView<
        'a,
        ::buffa::EnumValue<super::super::Permission>,
    >,
    /// Field 2: `is_public`
    pub is_public: ::core::option::Option<bool>,
    /// Field 3: `public_url`
    pub public_url: ::buffa::RepeatedView<'a, &'a str>,
    /// Field 4: `csrf_token_header`
    pub csrf_token_header: ::core::option::Option<&'a str>,
    /// Field 5: `csrf_token_cookie`
    pub csrf_token_cookie: ::core::option::Option<&'a str>,
    /// Field 6: `response_cors_headers` (map)
    pub response_cors_headers: ::buffa::MapView<'a, &'a str, &'a str>,
    /// Field 7: `enforce_csrf`
    pub enforce_csrf: bool,
    /// Field 8: `is_frontend`
    pub is_frontend: ::core::option::Option<bool>,
    /// Field 9: `frontend_static_file`
    pub frontend_static_file: ::core::option::Option<&'a str>,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for PermissionsView<'a> {
    type Owned = super::super::Permissions;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.is_public = Some(::buffa::types::decode_bool(&mut cur)?);
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.csrf_token_header = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.csrf_token_cookie = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.enforce_csrf = ::buffa::types::decode_bool(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.is_frontend = Some(::buffa::types::decode_bool(&mut cur)?);
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.frontend_static_file = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            1u32 => {
                if tag.wire_type() == ::buffa::encoding::WireType::LengthDelimited {
                    let payload = ::buffa::types::borrow_bytes(&mut cur)?;
                    view.allow_role.reserve(::buffa::encoding::count_varints(payload));
                    let mut pcur: &[u8] = payload;
                    while !pcur.is_empty() {
                        view.allow_role
                            .push(
                                ::buffa::EnumValue::from(
                                    ::buffa::types::decode_int32_packed(&mut pcur)?,
                                ),
                            );
                    }
                } else if tag.wire_type() == ::buffa::encoding::WireType::Varint {
                    view.allow_role
                        .push(
                            ::buffa::EnumValue::from(
                                ::buffa::types::decode_int32(&mut cur)?,
                            ),
                        );
                } else {
                    return Err(
                        ::buffa::encoding::wire_type_mismatch(
                            tag,
                            ::buffa::encoding::WireType::LengthDelimited,
                        ),
                    );
                }
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __elem = ::buffa::types::borrow_str(&mut cur)?;
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&__elem),
                )?;
                view.public_url.push(__elem);
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let entry_bytes = ::buffa::types::borrow_bytes(&mut cur)?;
                let mut entry_cur: &'a [u8] = entry_bytes;
                let mut key = "";
                let mut val = "";
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&key)
                        + ::buffa::__private::element_footprint(&val),
                )?;
                while !entry_cur.is_empty() {
                    let entry_tag = ::buffa::encoding::Tag::decode(&mut entry_cur)?;
                    match entry_tag.field_number() {
                        1 => {
                            ::buffa::encoding::check_wire_type(
                                entry_tag,
                                ::buffa::encoding::WireType::LengthDelimited,
                            )?;
                            key = ::buffa::types::borrow_str(&mut entry_cur)?;
                        }
                        2 => {
                            ::buffa::encoding::check_wire_type(
                                entry_tag,
                                ::buffa::encoding::WireType::LengthDelimited,
                            )?;
                            val = ::buffa::types::borrow_str(&mut entry_cur)?;
                        }
                        _ => {
                            ::buffa::encoding::skip_field_depth(
                                entry_tag,
                                &mut entry_cur,
                                ctx.depth(),
                            )?;
                        }
                    }
                }
                view.response_cors_headers.push(key, val);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::Permissions, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::Permissions, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::Permissions {
            allow_role: self.allow_role.to_vec(),
            is_public: self.is_public,
            public_url: self.public_url.iter().map(|s| s.to_string()).collect(),
            csrf_token_header: self.csrf_token_header.map(|s| s.to_string()),
            csrf_token_cookie: self.csrf_token_cookie.map(|s| s.to_string()),
            response_cors_headers: self
                .response_cors_headers
                .iter()
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
            enforce_csrf: self.enforce_csrf,
            is_frontend: self.is_frontend,
            frontend_static_file: self.frontend_static_file.map(|s| s.to_string()),
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PermissionsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.allow_role.is_empty() {
            let payload: u64 = self
                .allow_role
                .iter()
                .map(|v| ::buffa::types::int32_encoded_len(v.to_i32()) as u64)
                .sum::<u64>();
            size += 1u64 + ::buffa::encoding::varint_len(payload) as u64 + payload;
        }
        if self.is_public.is_some() {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        for v in &self.public_url {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if let Some(ref v) = self.csrf_token_header {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if let Some(ref v) = self.csrf_token_cookie {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        #[allow(clippy::for_kv_map)]
        for (k, v) in &self.response_cors_headers {
            let entry_size: u64 = 1u64 + ::buffa::types::string_encoded_len(k) as u64
                + 1u64 + ::buffa::types::string_encoded_len(v) as u64;
            size += 1u64 + ::buffa::encoding::varint_len(entry_size) as u64 + entry_size;
        }
        if self.enforce_csrf {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.is_frontend.is_some() {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if let Some(ref v) = self.frontend_static_file {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.allow_role.is_empty() {
            let payload: u64 = self
                .allow_role
                .iter()
                .map(|v| ::buffa::types::int32_encoded_len(v.to_i32()) as u64)
                .sum::<u64>();
            ::buffa::types::put_len_delimited_header(1u32, payload, buf);
            for v in &self.allow_role {
                ::buffa::types::encode_int32(v.to_i32(), buf);
            }
        }
        if let Some(v) = self.is_public {
            ::buffa::types::put_bool_field(2u32, v, buf);
        }
        for v in &self.public_url {
            ::buffa::types::put_string_field(3u32, v, buf);
        }
        if let Some(ref v) = self.csrf_token_header {
            ::buffa::types::put_string_field(4u32, v, buf);
        }
        if let Some(ref v) = self.csrf_token_cookie {
            ::buffa::types::put_string_field(5u32, v, buf);
        }
        for (k, v) in &self.response_cors_headers {
            let entry_size: u64 = 1u64 + ::buffa::types::string_encoded_len(k) as u64
                + 1u64 + ::buffa::types::string_encoded_len(v) as u64;
            ::buffa::encoding::Tag::new(
                    6u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(entry_size, buf);
            ::buffa::encoding::Tag::new(
                    1u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(k, buf);
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(v, buf);
        }
        if self.enforce_csrf {
            ::buffa::types::put_bool_field(7u32, self.enforce_csrf, buf);
        }
        if let Some(v) = self.is_frontend {
            ::buffa::types::put_bool_field(8u32, v, buf);
        }
        if let Some(ref v) = self.frontend_static_file {
            ::buffa::types::put_string_field(9u32, v, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for PermissionsView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !self.allow_role.is_empty() {
            __map
                .serialize_entry(
                    "allowRole",
                    &::buffa::json_helpers::EnumSeqJson(&self.allow_role),
                )?;
        }
        if let ::core::option::Option::Some(__v) = self.is_public {
            __map.serialize_entry("isPublic", &__v)?;
        }
        if !self.public_url.is_empty() {
            __map.serialize_entry("publicUrl", &*self.public_url)?;
        }
        if let ::core::option::Option::Some(__v) = self.csrf_token_header {
            __map.serialize_entry("csrfTokenHeader", __v)?;
        }
        if let ::core::option::Option::Some(__v) = self.csrf_token_cookie {
            __map.serialize_entry("csrfTokenCookie", __v)?;
        }
        if !self.response_cors_headers.is_empty() {
            struct _WM<'__a, '__x>(&'__x ::buffa::MapView<'__x, &'__a str, &'__a str>);
            impl<'__a> ::serde::Serialize for _WM<'__a, '_> {
                fn serialize<__S: ::serde::Serializer>(
                    &self,
                    __s: __S,
                ) -> ::core::result::Result<__S::Ok, __S::Error> {
                    use ::serde::ser::SerializeMap as _;
                    let mut __m = __s
                        .serialize_map(::core::option::Option::Some(self.0.len()))?;
                    for (k, v) in self.0.iter_unique() {
                        __m.serialize_entry(k, v)?;
                    }
                    __m.end()
                }
            }
            __map
                .serialize_entry(
                    "responseCorsHeaders",
                    &_WM(&self.response_cors_headers),
                )?;
        }
        if self.enforce_csrf {
            __map.serialize_entry("enforceCsrf", &self.enforce_csrf)?;
        }
        if let ::core::option::Option::Some(__v) = self.is_frontend {
            __map.serialize_entry("isFrontend", &__v)?;
        }
        if let ::core::option::Option::Some(__v) = self.frontend_static_file {
            __map.serialize_entry("frontendStaticFile", __v)?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for PermissionsView<'a> {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "Permissions";
    const FULL_NAME: &'static str = "auth.v2.Permissions";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.Permissions";
}
::buffa::impl_default_view_instance!(PermissionsView);
::buffa::impl_view_reborrow!(PermissionsView);
/** Self-contained, `'static` owned view of a `Permissions` message.

 Wraps [`::buffa::OwnedView`]`<`[`PermissionsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PermissionsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PermissionsOwnedView(::buffa::OwnedView<PermissionsView<'static>>);
impl PermissionsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PermissionsOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PermissionsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::Permissions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PermissionsOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`PermissionsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PermissionsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::Permissions {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `allow_role`
    #[must_use]
    pub fn allow_role(
        &self,
    ) -> &::buffa::RepeatedView<'_, ::buffa::EnumValue<super::super::Permission>> {
        &self.0.reborrow().allow_role
    }
    /// Field 2: `is_public`
    #[must_use]
    pub fn is_public(&self) -> ::core::option::Option<bool> {
        self.0.reborrow().is_public
    }
    /// Field 3: `public_url`
    #[must_use]
    pub fn public_url(&self) -> &::buffa::RepeatedView<'_, &'_ str> {
        &self.0.reborrow().public_url
    }
    /// Field 4: `csrf_token_header`
    #[must_use]
    pub fn csrf_token_header(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().csrf_token_header
    }
    /// Field 5: `csrf_token_cookie`
    #[must_use]
    pub fn csrf_token_cookie(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().csrf_token_cookie
    }
    /// Field 6: `response_cors_headers` (map)
    #[must_use]
    pub fn response_cors_headers(&self) -> &::buffa::MapView<'_, &'_ str, &'_ str> {
        &self.0.reborrow().response_cors_headers
    }
    /// Field 7: `enforce_csrf`
    #[must_use]
    pub fn enforce_csrf(&self) -> bool {
        self.0.reborrow().enforce_csrf
    }
    /// Field 8: `is_frontend`
    #[must_use]
    pub fn is_frontend(&self) -> ::core::option::Option<bool> {
        self.0.reborrow().is_frontend
    }
    /// Field 9: `frontend_static_file`
    #[must_use]
    pub fn frontend_static_file(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().frontend_static_file
    }
}
impl ::core::convert::From<::buffa::OwnedView<PermissionsView<'static>>>
for PermissionsOwnedView {
    fn from(inner: ::buffa::OwnedView<PermissionsView<'static>>) -> Self {
        PermissionsOwnedView(inner)
    }
}
impl ::core::convert::From<PermissionsOwnedView>
for ::buffa::OwnedView<PermissionsView<'static>> {
    fn from(wrapper: PermissionsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PermissionsView<'static>>>
for PermissionsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PermissionsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::Permissions {
    type View<'a> = PermissionsView<'a>;
    type ViewHandle = PermissionsOwnedView;
}
impl ::serde::Serialize for PermissionsOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectMessage for PermissionsView<'a> {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        super::super::__buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        super::super::__buffa::reflect::descriptor_pool()
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            1u32 => ::buffa_descriptor::reflect::ValueRef::List(&self.allow_role),
            2u32 => {
                ::buffa_descriptor::reflect::ValueRef::Bool(
                    self.is_public.unwrap_or(false),
                )
            }
            3u32 => ::buffa_descriptor::reflect::ValueRef::List(&self.public_url),
            4u32 => {
                ::buffa_descriptor::reflect::ValueRef::String(
                    self.csrf_token_header.unwrap_or(""),
                )
            }
            5u32 => {
                ::buffa_descriptor::reflect::ValueRef::String(
                    self.csrf_token_cookie.unwrap_or(""),
                )
            }
            6u32 => {
                ::buffa_descriptor::reflect::ValueRef::Map(&self.response_cors_headers)
            }
            7u32 => ::buffa_descriptor::reflect::ValueRef::Bool(self.enforce_csrf),
            8u32 => {
                ::buffa_descriptor::reflect::ValueRef::Bool(
                    self.is_frontend.unwrap_or(false),
                )
            }
            9u32 => {
                ::buffa_descriptor::reflect::ValueRef::String(
                    self.frontend_static_file.unwrap_or(""),
                )
            }
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this view's reflect get()", field
                    .number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            1u32 => !::buffa::RepeatedView::is_empty(&self.allow_role),
            2u32 => self.is_public.is_some(),
            3u32 => !::buffa::RepeatedView::is_empty(&self.public_url),
            4u32 => self.csrf_token_header.is_some(),
            5u32 => self.csrf_token_cookie.is_some(),
            6u32 => !::buffa::MapView::is_empty(&self.response_cors_headers),
            7u32 => self.enforce_csrf,
            8u32 => self.is_frontend.is_some(),
            9u32 => self.frontend_static_file.is_some(),
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        let bytes = ::buffa::ViewEncode::encode_to_vec(self);
        let options = ::buffa::DecodeOptions::new()
            .with_element_memory_limit(
                bytes
                    .len()
                    .saturating_mul(128)
                    .max(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT),
            )
            .with_unknown_field_limit(
                bytes.len().max(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT),
            );
        ::buffa_descriptor::reflect::DynamicMessage::decode_with_options(
                ::buffa::alloc::sync::Arc::clone(
                    super::super::__buffa::reflect::descriptor_pool(),
                ),
                Self::__buffa_reflect_message_index(),
                &bytes,
                &options,
            )
            .expect("view re-encodes to bytes decodable against its own descriptor")
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectElement for PermissionsView<'a> {
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl<'a> PermissionsView<'a> {
    /// Memoized `MessageIndex` for this view's message type, resolved
    /// once against the package's embedded descriptor pool. An inherent
    /// associated fn (not a free fn) so sibling views in the same module
    /// do not collide.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                super::super::__buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated view type is registered in the embedded descriptor pool",
                    )
            })
    }
}
