// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/jwt.proto

#[derive(Clone, Debug, Default)]
pub struct SmallDataView<'a> {
    /// Field 1: `user_id`
    pub user_id: i64,
    /// Field 2: `username`
    pub username: &'a str,
    /// Field 3: `first_name`
    pub first_name: &'a str,
    /// Field 4: `last_name`
    pub last_name: ::core::option::Option<&'a str>,
    /// Field 5: `permissions`
    pub permissions: i64,
    /// Field 6: `promotion`
    pub promotion: i32,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for SmallDataView<'a> {
    type Owned = super::super::SmallData;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.user_id = ::buffa::types::decode_int64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.username = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.first_name = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.last_name = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.permissions = ::buffa::types::decode_int64(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.promotion = ::buffa::types::decode_int32(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::SmallData, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::SmallData, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::SmallData {
            user_id: self.user_id,
            username: self.username.to_string(),
            first_name: self.first_name.to_string(),
            last_name: self.last_name.map(|s| s.to_string()),
            permissions: self.permissions,
            promotion: self.promotion,
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for SmallDataView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.user_id != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.user_id) as u64;
        }
        if !self.username.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.username) as u64;
        }
        if !self.first_name.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.first_name) as u64;
        }
        if let Some(ref v) = self.last_name {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if self.permissions != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.permissions) as u64;
        }
        if self.promotion != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.promotion) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.user_id != 0i64 {
            ::buffa::types::put_int64_field(1u32, self.user_id, buf);
        }
        if !self.username.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.username, buf);
        }
        if !self.first_name.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.first_name, buf);
        }
        if let Some(ref v) = self.last_name {
            ::buffa::types::put_string_field(4u32, v, buf);
        }
        if self.permissions != 0i64 {
            ::buffa::types::put_int64_field(5u32, self.permissions, buf);
        }
        if self.promotion != 0i32 {
            ::buffa::types::put_int32_field(6u32, self.promotion, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for SmallDataView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.user_id) {
            __map
                .serialize_entry(
                    "userId",
                    &::buffa::json_helpers::ProtoJson(&self.user_id),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.username) {
            __map.serialize_entry("username", self.username)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.first_name) {
            __map.serialize_entry("firstName", self.first_name)?;
        }
        if let ::core::option::Option::Some(__v) = self.last_name {
            __map.serialize_entry("lastName", __v)?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.permissions) {
            __map
                .serialize_entry(
                    "permissions",
                    &::buffa::json_helpers::ProtoJson(&self.permissions),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i32(&self.promotion) {
            __map
                .serialize_entry(
                    "promotion",
                    &::buffa::json_helpers::ProtoJson(&self.promotion),
                )?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for SmallDataView<'a> {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "SmallData";
    const FULL_NAME: &'static str = "auth.v2.SmallData";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.SmallData";
}
::buffa::impl_default_view_instance!(SmallDataView);
::buffa::impl_view_reborrow!(SmallDataView);
/** Self-contained, `'static` owned view of a `SmallData` message.

 Wraps [`::buffa::OwnedView`]`<`[`SmallDataView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`SmallDataView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct SmallDataOwnedView(::buffa::OwnedView<SmallDataView<'static>>);
impl SmallDataOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SmallDataOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SmallDataOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::SmallData,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SmallDataOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`SmallDataView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &SmallDataView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::SmallData {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `user_id`
    #[must_use]
    pub fn user_id(&self) -> i64 {
        self.0.reborrow().user_id
    }
    /// Field 2: `username`
    #[must_use]
    pub fn username(&self) -> &'_ str {
        self.0.reborrow().username
    }
    /// Field 3: `first_name`
    #[must_use]
    pub fn first_name(&self) -> &'_ str {
        self.0.reborrow().first_name
    }
    /// Field 4: `last_name`
    #[must_use]
    pub fn last_name(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().last_name
    }
    /// Field 5: `permissions`
    #[must_use]
    pub fn permissions(&self) -> i64 {
        self.0.reborrow().permissions
    }
    /// Field 6: `promotion`
    #[must_use]
    pub fn promotion(&self) -> i32 {
        self.0.reborrow().promotion
    }
}
impl ::core::convert::From<::buffa::OwnedView<SmallDataView<'static>>>
for SmallDataOwnedView {
    fn from(inner: ::buffa::OwnedView<SmallDataView<'static>>) -> Self {
        SmallDataOwnedView(inner)
    }
}
impl ::core::convert::From<SmallDataOwnedView>
for ::buffa::OwnedView<SmallDataView<'static>> {
    fn from(wrapper: SmallDataOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<SmallDataView<'static>>>
for SmallDataOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<SmallDataView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::SmallData {
    type View<'a> = SmallDataView<'a>;
    type ViewHandle = SmallDataOwnedView;
}
impl ::serde::Serialize for SmallDataOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectMessage for SmallDataView<'a> {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        super::super::__buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        super::super::__buffa::reflect::descriptor_pool()
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            1u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.user_id),
            2u32 => ::buffa_descriptor::reflect::ValueRef::String(self.username),
            3u32 => ::buffa_descriptor::reflect::ValueRef::String(self.first_name),
            4u32 => {
                ::buffa_descriptor::reflect::ValueRef::String(
                    self.last_name.unwrap_or(""),
                )
            }
            5u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.permissions),
            6u32 => ::buffa_descriptor::reflect::ValueRef::I32(self.promotion),
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this view's reflect get()", field
                    .number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            1u32 => self.user_id != 0,
            2u32 => !self.username.is_empty(),
            3u32 => !self.first_name.is_empty(),
            4u32 => self.last_name.is_some(),
            5u32 => self.permissions != 0,
            6u32 => self.promotion != 0,
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        let bytes = ::buffa::ViewEncode::encode_to_vec(self);
        let options = ::buffa::DecodeOptions::new()
            .with_element_memory_limit(
                bytes
                    .len()
                    .saturating_mul(128)
                    .max(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT),
            )
            .with_unknown_field_limit(
                bytes.len().max(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT),
            );
        ::buffa_descriptor::reflect::DynamicMessage::decode_with_options(
                ::buffa::alloc::sync::Arc::clone(
                    super::super::__buffa::reflect::descriptor_pool(),
                ),
                Self::__buffa_reflect_message_index(),
                &bytes,
                &options,
            )
            .expect("view re-encodes to bytes decodable against its own descriptor")
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectElement for SmallDataView<'a> {
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl<'a> SmallDataView<'a> {
    /// Memoized `MessageIndex` for this view's message type, resolved
    /// once against the package's embedded descriptor pool. An inherent
    /// associated fn (not a free fn) so sibling views in the same module
    /// do not collide.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                super::super::__buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated view type is registered in the embedded descriptor pool",
                    )
            })
    }
}
#[derive(Clone, Debug, Default)]
pub struct JwtClaimsView<'a> {
    /// Issuer
    ///
    /// Field 1: `iss`
    pub iss: &'a str,
    /// Subject
    ///
    /// Field 2: `sub`
    pub sub: &'a str,
    /// Audience
    ///
    /// Field 3: `aud`
    pub aud: &'a str,
    /// Expiration Time (Unix timestamp)
    ///
    /// Field 4: `exp`
    pub exp: i64,
    /// Not Before (Unix timestamp)
    ///
    /// Field 5: `nbf`
    pub nbf: i64,
    /// Issued At (Unix timestamp)
    ///
    /// Field 6: `iat`
    pub iat: i64,
    /// JWT ID
    ///
    /// Field 7: `jti`
    pub jti: &'a str,
    /// Field 8: `temporary`
    pub temporary: bool,
    /// Field 9: `temporary_recheck_after`
    pub temporary_recheck_after: ::core::option::Option<i64>,
    /// Field 10: `data`
    pub data: ::buffa::MessageFieldView<super::super::__buffa::view::SmallDataView<'a>>,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for JwtClaimsView<'a> {
    type Owned = super::super::JwtClaims;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.iss = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.sub = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.aud = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.exp = ::buffa::types::decode_int64(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.nbf = ::buffa::types::decode_int64(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.iat = ::buffa::types::decode_int64(&mut cur)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.jti = ::buffa::types::borrow_str(&mut cur)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.temporary = ::buffa::types::decode_bool(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.temporary_recheck_after = Some(
                    ::buffa::types::decode_int64(&mut cur)?,
                );
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.data.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.data = ::buffa::MessageFieldView::set(
                            <super::super::__buffa::view::SmallDataView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::JwtClaims, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::JwtClaims, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::JwtClaims {
            iss: self.iss.to_string(),
            sub: self.sub.to_string(),
            aud: self.aud.to_string(),
            exp: self.exp,
            nbf: self.nbf,
            iat: self.iat,
            jti: self.jti.to_string(),
            temporary: self.temporary,
            temporary_recheck_after: self.temporary_recheck_after,
            data: match self.data.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        super::super::SmallData,
                        ::buffa::Inline<super::super::SmallData>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for JwtClaimsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.iss.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.iss) as u64;
        }
        if !self.sub.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.sub) as u64;
        }
        if !self.aud.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.aud) as u64;
        }
        if self.exp != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.exp) as u64;
        }
        if self.nbf != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.nbf) as u64;
        }
        if self.iat != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.iat) as u64;
        }
        if !self.jti.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.jti) as u64;
        }
        if self.temporary {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if let Some(v) = self.temporary_recheck_after {
            size += 1u64 + ::buffa::types::int64_encoded_len(v) as u64;
        }
        if self.data.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.data.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.iss.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.iss, buf);
        }
        if !self.sub.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.sub, buf);
        }
        if !self.aud.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.aud, buf);
        }
        if self.exp != 0i64 {
            ::buffa::types::put_int64_field(4u32, self.exp, buf);
        }
        if self.nbf != 0i64 {
            ::buffa::types::put_int64_field(5u32, self.nbf, buf);
        }
        if self.iat != 0i64 {
            ::buffa::types::put_int64_field(6u32, self.iat, buf);
        }
        if !self.jti.is_empty() {
            ::buffa::types::put_string_field(7u32, &self.jti, buf);
        }
        if self.temporary {
            ::buffa::types::put_bool_field(8u32, self.temporary, buf);
        }
        if let Some(v) = self.temporary_recheck_after {
            ::buffa::types::put_int64_field(9u32, v, buf);
        }
        if self.data.is_set() {
            ::buffa::types::put_len_delimited_header(
                10u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.data.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for JwtClaimsView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_empty_str(self.iss) {
            __map.serialize_entry("iss", self.iss)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.sub) {
            __map.serialize_entry("sub", self.sub)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.aud) {
            __map.serialize_entry("aud", self.aud)?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.exp) {
            __map.serialize_entry("exp", &::buffa::json_helpers::ProtoJson(&self.exp))?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.nbf) {
            __map.serialize_entry("nbf", &::buffa::json_helpers::ProtoJson(&self.nbf))?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.iat) {
            __map.serialize_entry("iat", &::buffa::json_helpers::ProtoJson(&self.iat))?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.jti) {
            __map.serialize_entry("jti", self.jti)?;
        }
        if self.temporary {
            __map.serialize_entry("temporary", &self.temporary)?;
        }
        if let ::core::option::Option::Some(__v) = self.temporary_recheck_after {
            __map
                .serialize_entry(
                    "temporaryRecheckAfter",
                    &::buffa::json_helpers::ProtoJson(&__v),
                )?;
        }
        {
            if let ::core::option::Option::Some(__v) = self.data.as_option() {
                __map.serialize_entry("data", __v)?;
            }
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for JwtClaimsView<'a> {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "JwtClaims";
    const FULL_NAME: &'static str = "auth.v2.JwtClaims";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.JwtClaims";
}
::buffa::impl_default_view_instance!(JwtClaimsView);
::buffa::impl_view_reborrow!(JwtClaimsView);
/** Self-contained, `'static` owned view of a `JwtClaims` message.

 Wraps [`::buffa::OwnedView`]`<`[`JwtClaimsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`JwtClaimsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct JwtClaimsOwnedView(::buffa::OwnedView<JwtClaimsView<'static>>);
impl JwtClaimsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            JwtClaimsOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            JwtClaimsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::JwtClaims,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            JwtClaimsOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`JwtClaimsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &JwtClaimsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::JwtClaims {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Issuer
    ///
    /// Field 1: `iss`
    #[must_use]
    pub fn iss(&self) -> &'_ str {
        self.0.reborrow().iss
    }
    /// Subject
    ///
    /// Field 2: `sub`
    #[must_use]
    pub fn sub(&self) -> &'_ str {
        self.0.reborrow().sub
    }
    /// Audience
    ///
    /// Field 3: `aud`
    #[must_use]
    pub fn aud(&self) -> &'_ str {
        self.0.reborrow().aud
    }
    /// Expiration Time (Unix timestamp)
    ///
    /// Field 4: `exp`
    #[must_use]
    pub fn exp(&self) -> i64 {
        self.0.reborrow().exp
    }
    /// Not Before (Unix timestamp)
    ///
    /// Field 5: `nbf`
    #[must_use]
    pub fn nbf(&self) -> i64 {
        self.0.reborrow().nbf
    }
    /// Issued At (Unix timestamp)
    ///
    /// Field 6: `iat`
    #[must_use]
    pub fn iat(&self) -> i64 {
        self.0.reborrow().iat
    }
    /// JWT ID
    ///
    /// Field 7: `jti`
    #[must_use]
    pub fn jti(&self) -> &'_ str {
        self.0.reborrow().jti
    }
    /// Field 8: `temporary`
    #[must_use]
    pub fn temporary(&self) -> bool {
        self.0.reborrow().temporary
    }
    /// Field 9: `temporary_recheck_after`
    #[must_use]
    pub fn temporary_recheck_after(&self) -> ::core::option::Option<i64> {
        self.0.reborrow().temporary_recheck_after
    }
    /// Field 10: `data`
    #[must_use]
    pub fn data(
        &self,
    ) -> &::buffa::MessageFieldView<super::super::__buffa::view::SmallDataView<'_>> {
        &self.0.reborrow().data
    }
}
impl ::core::convert::From<::buffa::OwnedView<JwtClaimsView<'static>>>
for JwtClaimsOwnedView {
    fn from(inner: ::buffa::OwnedView<JwtClaimsView<'static>>) -> Self {
        JwtClaimsOwnedView(inner)
    }
}
impl ::core::convert::From<JwtClaimsOwnedView>
for ::buffa::OwnedView<JwtClaimsView<'static>> {
    fn from(wrapper: JwtClaimsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<JwtClaimsView<'static>>>
for JwtClaimsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<JwtClaimsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::JwtClaims {
    type View<'a> = JwtClaimsView<'a>;
    type ViewHandle = JwtClaimsOwnedView;
}
impl ::serde::Serialize for JwtClaimsOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectMessage for JwtClaimsView<'a> {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        super::super::__buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        super::super::__buffa::reflect::descriptor_pool()
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            1u32 => ::buffa_descriptor::reflect::ValueRef::String(self.iss),
            2u32 => ::buffa_descriptor::reflect::ValueRef::String(self.sub),
            3u32 => ::buffa_descriptor::reflect::ValueRef::String(self.aud),
            4u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.exp),
            5u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.nbf),
            6u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.iat),
            7u32 => ::buffa_descriptor::reflect::ValueRef::String(self.jti),
            8u32 => ::buffa_descriptor::reflect::ValueRef::Bool(self.temporary),
            9u32 => {
                ::buffa_descriptor::reflect::ValueRef::I64(
                    self.temporary_recheck_after.unwrap_or(0),
                )
            }
            10u32 => {
                ::buffa_descriptor::reflect::ValueRef::Message(
                    ::buffa_descriptor::reflect::ReflectCow::Borrowed(&*self.data),
                )
            }
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this view's reflect get()", field
                    .number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            1u32 => !self.iss.is_empty(),
            2u32 => !self.sub.is_empty(),
            3u32 => !self.aud.is_empty(),
            4u32 => self.exp != 0,
            5u32 => self.nbf != 0,
            6u32 => self.iat != 0,
            7u32 => !self.jti.is_empty(),
            8u32 => self.temporary,
            9u32 => self.temporary_recheck_after.is_some(),
            10u32 => self.data.is_set(),
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        let bytes = ::buffa::ViewEncode::encode_to_vec(self);
        let options = ::buffa::DecodeOptions::new()
            .with_element_memory_limit(
                bytes
                    .len()
                    .saturating_mul(128)
                    .max(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT),
            )
            .with_unknown_field_limit(
                bytes.len().max(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT),
            );
        ::buffa_descriptor::reflect::DynamicMessage::decode_with_options(
                ::buffa::alloc::sync::Arc::clone(
                    super::super::__buffa::reflect::descriptor_pool(),
                ),
                Self::__buffa_reflect_message_index(),
                &bytes,
                &options,
            )
            .expect("view re-encodes to bytes decodable against its own descriptor")
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectElement for JwtClaimsView<'a> {
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl<'a> JwtClaimsView<'a> {
    /// Memoized `MessageIndex` for this view's message type, resolved
    /// once against the package's embedded descriptor pool. An inherent
    /// associated fn (not a free fn) so sibling views in the same module
    /// do not collide.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                super::super::__buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated view type is registered in the embedded descriptor pool",
                    )
            })
    }
}
#[derive(Clone, Debug, Default)]
pub struct GetCSRFTokenRequestView<'a> {
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for GetCSRFTokenRequestView<'a> {
    type Owned = super::super::GetCSRFTokenRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::GetCSRFTokenRequest,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::GetCSRFTokenRequest,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::GetCSRFTokenRequest {
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for GetCSRFTokenRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for GetCSRFTokenRequestView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for GetCSRFTokenRequestView<'a> {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "GetCSRFTokenRequest";
    const FULL_NAME: &'static str = "auth.v2.GetCSRFTokenRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.GetCSRFTokenRequest";
}
::buffa::impl_default_view_instance!(GetCSRFTokenRequestView);
::buffa::impl_view_reborrow!(GetCSRFTokenRequestView);
/** Self-contained, `'static` owned view of a `GetCSRFTokenRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`GetCSRFTokenRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`GetCSRFTokenRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct GetCSRFTokenRequestOwnedView(
    ::buffa::OwnedView<GetCSRFTokenRequestView<'static>>,
);
impl GetCSRFTokenRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetCSRFTokenRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetCSRFTokenRequestOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::GetCSRFTokenRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetCSRFTokenRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`GetCSRFTokenRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &GetCSRFTokenRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::GetCSRFTokenRequest {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
}
impl ::core::convert::From<::buffa::OwnedView<GetCSRFTokenRequestView<'static>>>
for GetCSRFTokenRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<GetCSRFTokenRequestView<'static>>) -> Self {
        GetCSRFTokenRequestOwnedView(inner)
    }
}
impl ::core::convert::From<GetCSRFTokenRequestOwnedView>
for ::buffa::OwnedView<GetCSRFTokenRequestView<'static>> {
    fn from(wrapper: GetCSRFTokenRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<GetCSRFTokenRequestView<'static>>>
for GetCSRFTokenRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<GetCSRFTokenRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::GetCSRFTokenRequest {
    type View<'a> = GetCSRFTokenRequestView<'a>;
    type ViewHandle = GetCSRFTokenRequestOwnedView;
}
impl ::serde::Serialize for GetCSRFTokenRequestOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectMessage for GetCSRFTokenRequestView<'a> {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        super::super::__buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        super::super::__buffa::reflect::descriptor_pool()
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this view's reflect get()", field
                    .number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        let bytes = ::buffa::ViewEncode::encode_to_vec(self);
        let options = ::buffa::DecodeOptions::new()
            .with_element_memory_limit(
                bytes
                    .len()
                    .saturating_mul(128)
                    .max(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT),
            )
            .with_unknown_field_limit(
                bytes.len().max(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT),
            );
        ::buffa_descriptor::reflect::DynamicMessage::decode_with_options(
                ::buffa::alloc::sync::Arc::clone(
                    super::super::__buffa::reflect::descriptor_pool(),
                ),
                Self::__buffa_reflect_message_index(),
                &bytes,
                &options,
            )
            .expect("view re-encodes to bytes decodable against its own descriptor")
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectElement for GetCSRFTokenRequestView<'a> {
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl<'a> GetCSRFTokenRequestView<'a> {
    /// Memoized `MessageIndex` for this view's message type, resolved
    /// once against the package's embedded descriptor pool. An inherent
    /// associated fn (not a free fn) so sibling views in the same module
    /// do not collide.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                super::super::__buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated view type is registered in the embedded descriptor pool",
                    )
            })
    }
}
#[derive(Clone, Debug, Default)]
pub struct GetCSRFTokenResponseView<'a> {
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for GetCSRFTokenResponseView<'a> {
    type Owned = super::super::GetCSRFTokenResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::GetCSRFTokenResponse,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::GetCSRFTokenResponse,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::GetCSRFTokenResponse {
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for GetCSRFTokenResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for GetCSRFTokenResponseView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for GetCSRFTokenResponseView<'a> {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "GetCSRFTokenResponse";
    const FULL_NAME: &'static str = "auth.v2.GetCSRFTokenResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.GetCSRFTokenResponse";
}
::buffa::impl_default_view_instance!(GetCSRFTokenResponseView);
::buffa::impl_view_reborrow!(GetCSRFTokenResponseView);
/** Self-contained, `'static` owned view of a `GetCSRFTokenResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`GetCSRFTokenResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`GetCSRFTokenResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct GetCSRFTokenResponseOwnedView(
    ::buffa::OwnedView<GetCSRFTokenResponseView<'static>>,
);
impl GetCSRFTokenResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetCSRFTokenResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetCSRFTokenResponseOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::GetCSRFTokenResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            GetCSRFTokenResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`GetCSRFTokenResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &GetCSRFTokenResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::GetCSRFTokenResponse {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
}
impl ::core::convert::From<::buffa::OwnedView<GetCSRFTokenResponseView<'static>>>
for GetCSRFTokenResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<GetCSRFTokenResponseView<'static>>) -> Self {
        GetCSRFTokenResponseOwnedView(inner)
    }
}
impl ::core::convert::From<GetCSRFTokenResponseOwnedView>
for ::buffa::OwnedView<GetCSRFTokenResponseView<'static>> {
    fn from(wrapper: GetCSRFTokenResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<GetCSRFTokenResponseView<'static>>>
for GetCSRFTokenResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<GetCSRFTokenResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::GetCSRFTokenResponse {
    type View<'a> = GetCSRFTokenResponseView<'a>;
    type ViewHandle = GetCSRFTokenResponseOwnedView;
}
impl ::serde::Serialize for GetCSRFTokenResponseOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectMessage for GetCSRFTokenResponseView<'a> {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        super::super::__buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        super::super::__buffa::reflect::descriptor_pool()
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this view's reflect get()", field
                    .number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        let bytes = ::buffa::ViewEncode::encode_to_vec(self);
        let options = ::buffa::DecodeOptions::new()
            .with_element_memory_limit(
                bytes
                    .len()
                    .saturating_mul(128)
                    .max(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT),
            )
            .with_unknown_field_limit(
                bytes.len().max(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT),
            );
        ::buffa_descriptor::reflect::DynamicMessage::decode_with_options(
                ::buffa::alloc::sync::Arc::clone(
                    super::super::__buffa::reflect::descriptor_pool(),
                ),
                Self::__buffa_reflect_message_index(),
                &bytes,
                &options,
            )
            .expect("view re-encodes to bytes decodable against its own descriptor")
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectElement for GetCSRFTokenResponseView<'a> {
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl<'a> GetCSRFTokenResponseView<'a> {
    /// Memoized `MessageIndex` for this view's message type, resolved
    /// once against the package's embedded descriptor pool. An inherent
    /// associated fn (not a free fn) so sibling views in the same module
    /// do not collide.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                super::super::__buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated view type is registered in the embedded descriptor pool",
                    )
            })
    }
}
