// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/auth_data.proto

#[derive(Clone, Debug, Default)]
pub struct DBUserView<'a> {
    /// Field 1: `id`
    pub id: i64,
    /// Field 2: `username`
    pub username: &'a str,
    /// Field 3: `first_name`
    pub first_name: &'a str,
    /// Field 4: `last_name`
    pub last_name: ::core::option::Option<&'a str>,
    /// Field 5: `discord_id`
    pub discord_id: &'a str,
    /// Field 6: `account_created_date`
    pub account_created_date: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 7: `account_modified_date`
    pub account_modified_date: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 8: `promotion`
    pub promotion: i32,
    /// Field 9: `permissions`
    pub permissions: i64,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> DBUserView<'a> {
    /// Decode from `buf`, enforcing a recursion depth limit for nested messages.
    ///
    /// Called by [`::buffa::MessageView::decode_view`] with [`::buffa::RECURSION_LIMIT`]
    /// and by generated sub-message decode arms with `depth - 1`.
    ///
    /// **Not part of the public API.** Named with a leading underscore to
    /// signal that it is for generated-code use only.
    #[doc(hidden)]
    pub fn _decode_depth(
        buf: &'a [u8],
        depth: u32,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let mut view = Self::default();
        view._merge_into_view(buf, depth)?;
        ::core::result::Result::Ok(view)
    }
    /// Merge fields from `buf` into this view (proto merge semantics).
    ///
    /// Repeated fields append; singular fields last-wins; singular
    /// MESSAGE fields merge recursively. Used by sub-message decode
    /// arms when the same field appears multiple times on the wire.
    ///
    /// **Not part of the public API.**
    #[doc(hidden)]
    pub fn _merge_into_view(
        &mut self,
        buf: &'a [u8],
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        let _ = depth;
        #[allow(unused_variables)]
        let view = self;
        let mut cur: &'a [u8] = buf;
        while !cur.is_empty() {
            let before_tag = cur;
            let tag = ::buffa::encoding::Tag::decode(&mut cur)?;
            match tag.field_number() {
                1u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 1u32,
                            expected: 0u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    view.id = ::buffa::types::decode_int64(&mut cur)?;
                }
                2u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 2u32,
                            expected: 2u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    view.username = ::buffa::types::borrow_str(&mut cur)?;
                }
                3u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 3u32,
                            expected: 2u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    view.first_name = ::buffa::types::borrow_str(&mut cur)?;
                }
                4u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 4u32,
                            expected: 2u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    view.last_name = Some(::buffa::types::borrow_str(&mut cur)?);
                }
                5u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 5u32,
                            expected: 2u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    view.discord_id = ::buffa::types::borrow_str(&mut cur)?;
                }
                6u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 6u32,
                            expected: 2u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    if depth == 0 {
                        return Err(::buffa::DecodeError::RecursionLimitExceeded);
                    }
                    let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                    match view.account_created_date.as_mut() {
                        Some(existing) => existing._merge_into_view(sub, depth - 1)?,
                        None => {
                            view.account_created_date = ::buffa::MessageFieldView::set(
                                ::buffa_types::google::protobuf::__buffa::view::TimestampView::_decode_depth(
                                    sub,
                                    depth - 1,
                                )?,
                            );
                        }
                    }
                }
                7u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 7u32,
                            expected: 2u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    if depth == 0 {
                        return Err(::buffa::DecodeError::RecursionLimitExceeded);
                    }
                    let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                    match view.account_modified_date.as_mut() {
                        Some(existing) => existing._merge_into_view(sub, depth - 1)?,
                        None => {
                            view.account_modified_date = ::buffa::MessageFieldView::set(
                                ::buffa_types::google::protobuf::__buffa::view::TimestampView::_decode_depth(
                                    sub,
                                    depth - 1,
                                )?,
                            );
                        }
                    }
                }
                8u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 8u32,
                            expected: 0u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    view.promotion = ::buffa::types::decode_int32(&mut cur)?;
                }
                9u32 => {
                    if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                        return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                            field_number: 9u32,
                            expected: 0u8,
                            actual: tag.wire_type() as u8,
                        });
                    }
                    view.permissions = ::buffa::types::decode_int64(&mut cur)?;
                }
                _ => {
                    ::buffa::encoding::skip_field_depth(tag, &mut cur, depth)?;
                    let span_len = before_tag.len() - cur.len();
                    view.__buffa_unknown_fields.push_raw(&before_tag[..span_len]);
                }
            }
        }
        ::core::result::Result::Ok(())
    }
}
impl<'a> ::buffa::MessageView<'a> for DBUserView<'a> {
    type Owned = super::super::DBUser;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        Self::_decode_depth(buf, ::buffa::RECURSION_LIMIT)
    }
    fn decode_view_with_limit(
        buf: &'a [u8],
        depth: u32,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        Self::_decode_depth(buf, depth)
    }
    fn to_owned_message(&self) -> super::super::DBUser {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> super::super::DBUser {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        super::super::DBUser {
            id: self.id,
            username: self.username.to_string(),
            first_name: self.first_name.to_string(),
            last_name: self.last_name.map(|s| s.to_string()),
            discord_id: self.discord_id.to_string(),
            account_created_date: match self.account_created_date.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                    >::some(v.to_owned_from_source(__buffa_src))
                }
                None => ::buffa::MessageField::none(),
            },
            account_modified_date: match self.account_modified_date.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                    >::some(v.to_owned_from_source(__buffa_src))
                }
                None => ::buffa::MessageField::none(),
            },
            promotion: self.promotion,
            permissions: self.permissions,
            __buffa_unknown_fields: self
                .__buffa_unknown_fields
                .to_owned()
                .unwrap_or_default()
                .into(),
            ..::core::default::Default::default()
        }
    }
}
impl<'a> ::buffa::ViewEncode<'a> for DBUserView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.id != 0i64 {
            size += 1u32 + ::buffa::types::int64_encoded_len(self.id) as u32;
        }
        if !self.username.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.username) as u32;
        }
        if !self.first_name.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.first_name) as u32;
        }
        if let Some(ref v) = self.last_name {
            size += 1u32 + ::buffa::types::string_encoded_len(v) as u32;
        }
        if !self.discord_id.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.discord_id) as u32;
        }
        if self.account_created_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_created_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.account_modified_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_modified_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.promotion != 0i32 {
            size += 1u32 + ::buffa::types::int32_encoded_len(self.promotion) as u32;
        }
        if self.permissions != 0i64 {
            size += 1u32 + ::buffa::types::int64_encoded_len(self.permissions) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.id != 0i64 {
            ::buffa::encoding::Tag::new(1u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_int64(self.id, buf);
        }
        if !self.username.is_empty() {
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.username, buf);
        }
        if !self.first_name.is_empty() {
            ::buffa::encoding::Tag::new(
                    3u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.first_name, buf);
        }
        if let Some(ref v) = self.last_name {
            ::buffa::encoding::Tag::new(
                    4u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(v, buf);
        }
        if !self.discord_id.is_empty() {
            ::buffa::encoding::Tag::new(
                    5u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.discord_id, buf);
        }
        if self.account_created_date.is_set() {
            ::buffa::encoding::Tag::new(
                    6u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
            self.account_created_date.write_to(__cache, buf);
        }
        if self.account_modified_date.is_set() {
            ::buffa::encoding::Tag::new(
                    7u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
            self.account_modified_date.write_to(__cache, buf);
        }
        if self.promotion != 0i32 {
            ::buffa::encoding::Tag::new(8u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_int32(self.promotion, buf);
        }
        if self.permissions != 0i64 {
            ::buffa::encoding::Tag::new(9u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_int64(self.permissions, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for DBUserView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.id) {
            struct _W(i64);
            impl ::serde::Serialize for _W {
                fn serialize<__S: ::serde::Serializer>(
                    &self,
                    __s: __S,
                ) -> ::core::result::Result<__S::Ok, __S::Error> {
                    ::buffa::json_helpers::int64::serialize(&self.0, __s)
                }
            }
            __map.serialize_entry("id", &_W(self.id))?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.username) {
            __map.serialize_entry("username", self.username)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.first_name) {
            __map.serialize_entry("firstName", self.first_name)?;
        }
        if let ::core::option::Option::Some(__v) = self.last_name {
            __map.serialize_entry("lastName", __v)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.discord_id) {
            __map.serialize_entry("discordId", self.discord_id)?;
        }
        {
            if let ::core::option::Option::Some(__v) = self
                .account_created_date
                .as_option()
            {
                __map.serialize_entry("accountCreatedDate", __v)?;
            }
        }
        {
            if let ::core::option::Option::Some(__v) = self
                .account_modified_date
                .as_option()
            {
                __map.serialize_entry("accountModifiedDate", __v)?;
            }
        }
        if !::buffa::json_helpers::skip_if::is_zero_i32(&self.promotion) {
            struct _W(i32);
            impl ::serde::Serialize for _W {
                fn serialize<__S: ::serde::Serializer>(
                    &self,
                    __s: __S,
                ) -> ::core::result::Result<__S::Ok, __S::Error> {
                    ::buffa::json_helpers::int32::serialize(&self.0, __s)
                }
            }
            __map.serialize_entry("promotion", &_W(self.promotion))?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.permissions) {
            struct _W(i64);
            impl ::serde::Serialize for _W {
                fn serialize<__S: ::serde::Serializer>(
                    &self,
                    __s: __S,
                ) -> ::core::result::Result<__S::Ok, __S::Error> {
                    ::buffa::json_helpers::int64::serialize(&self.0, __s)
                }
            }
            __map.serialize_entry("permissions", &_W(self.permissions))?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for DBUserView<'a> {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "DBUser";
    const FULL_NAME: &'static str = "auth.v2.DBUser";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.DBUser";
}
impl<'v> ::buffa::DefaultViewInstance for DBUserView<'v> {
    fn default_view_instance<'a>() -> &'a Self
    where
        Self: 'a,
    {
        static VALUE: ::buffa::__private::OnceBox<DBUserView<'static>> = ::buffa::__private::OnceBox::new();
        VALUE
            .get_or_init(|| ::buffa::alloc::boxed::Box::new(
                <DBUserView<'static>>::default(),
            ))
    }
}
impl ::buffa::ViewReborrow for DBUserView<'static> {
    type Reborrowed<'b> = DBUserView<'b>;
    fn reborrow<'b>(this: &'b Self) -> &'b Self::Reborrowed<'b> {
        this
    }
}
/** Self-contained, `'static` owned view of a `DBUser` message.

 Wraps [`::buffa::OwnedView`]`<`[`DBUserView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`DBUserView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct DBUserOwnedView(::buffa::OwnedView<DBUserView<'static>>);
impl DBUserOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(DBUserOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            DBUserOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::DBUser,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(DBUserOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`DBUserView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &DBUserView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::DBUser {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> i64 {
        self.0.reborrow().id
    }
    /// Field 2: `username`
    #[must_use]
    pub fn username(&self) -> &'_ str {
        self.0.reborrow().username
    }
    /// Field 3: `first_name`
    #[must_use]
    pub fn first_name(&self) -> &'_ str {
        self.0.reborrow().first_name
    }
    /// Field 4: `last_name`
    #[must_use]
    pub fn last_name(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().last_name
    }
    /// Field 5: `discord_id`
    #[must_use]
    pub fn discord_id(&self) -> &'_ str {
        self.0.reborrow().discord_id
    }
    /// Field 6: `account_created_date`
    #[must_use]
    pub fn account_created_date(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().account_created_date
    }
    /// Field 7: `account_modified_date`
    #[must_use]
    pub fn account_modified_date(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().account_modified_date
    }
    /// Field 8: `promotion`
    #[must_use]
    pub fn promotion(&self) -> i32 {
        self.0.reborrow().promotion
    }
    /// Field 9: `permissions`
    #[must_use]
    pub fn permissions(&self) -> i64 {
        self.0.reborrow().permissions
    }
}
impl ::core::convert::From<::buffa::OwnedView<DBUserView<'static>>> for DBUserOwnedView {
    fn from(inner: ::buffa::OwnedView<DBUserView<'static>>) -> Self {
        DBUserOwnedView(inner)
    }
}
impl ::core::convert::From<DBUserOwnedView> for ::buffa::OwnedView<DBUserView<'static>> {
    fn from(wrapper: DBUserOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<DBUserView<'static>>>
for DBUserOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<DBUserView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::DBUser {
    type View<'a> = DBUserView<'a>;
    type ViewHandle = DBUserOwnedView;
}
impl ::serde::Serialize for DBUserOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
