// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/auth_data.proto

#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct DBUser {
    /// Field 1: `id`
    #[serde(
        rename = "id",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub id: i64,
    /// Field 2: `username`
    #[serde(
        rename = "username",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub username: ::buffa::alloc::string::String,
    /// Field 3: `first_name`
    #[serde(
        rename = "firstName",
        alias = "first_name",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub first_name: ::buffa::alloc::string::String,
    /// Field 4: `last_name`
    #[serde(
        rename = "lastName",
        alias = "last_name",
        skip_serializing_if = "::core::option::Option::is_none"
    )]
    pub last_name: ::core::option::Option<::buffa::alloc::string::String>,
    /// Field 5: `discord_id`
    #[serde(
        rename = "discordId",
        alias = "discord_id",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub discord_id: ::buffa::alloc::string::String,
    /// Field 6: `account_created_date`
    #[serde(
        rename = "accountCreatedDate",
        alias = "account_created_date",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub account_created_date: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
    >,
    /// Field 7: `account_modified_date`
    #[serde(
        rename = "accountModifiedDate",
        alias = "account_modified_date",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub account_modified_date: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
    >,
    /// Field 8: `promotion`
    #[serde(
        rename = "promotion",
        with = "::buffa::json_helpers::int32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i32"
    )]
    pub promotion: i32,
    /// Field 9: `permissions`
    #[serde(
        rename = "permissions",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub permissions: i64,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for DBUser {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("DBUser")
            .field("id", &self.id)
            .field("username", &self.username)
            .field("first_name", &self.first_name)
            .field("last_name", &self.last_name)
            .field("discord_id", &self.discord_id)
            .field("account_created_date", &self.account_created_date)
            .field("account_modified_date", &self.account_modified_date)
            .field("promotion", &self.promotion)
            .field("permissions", &self.permissions)
            .finish()
    }
}
impl DBUser {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.DBUser";
}
impl DBUser {
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::last_name`] to `Some(value)`, consuming and returning `self`.
    pub fn with_last_name(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.last_name = Some(value.into());
        self
    }
}
impl ::buffa::DefaultInstance for DBUser {
    fn default_instance() -> &'static Self {
        static VALUE: ::buffa::__private::OnceBox<DBUser> = ::buffa::__private::OnceBox::new();
        VALUE.get_or_init(|| ::buffa::alloc::boxed::Box::new(Self::default()))
    }
}
impl ::buffa::MessageName for DBUser {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "DBUser";
    const FULL_NAME: &'static str = "auth.v2.DBUser";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.DBUser";
}
impl ::buffa::Message for DBUser {
    /// Returns the total encoded size in bytes.
    ///
    /// The result is a `u32`; the protobuf specification requires all
    /// messages to fit within 2 GiB (2,147,483,647 bytes), so a
    /// compliant message will never overflow this type.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u32;
        if self.id != 0i64 {
            size += 1u32 + ::buffa::types::int64_encoded_len(self.id) as u32;
        }
        if !self.username.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.username) as u32;
        }
        if !self.first_name.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.first_name) as u32;
        }
        if let Some(ref v) = self.last_name {
            size += 1u32 + ::buffa::types::string_encoded_len(v) as u32;
        }
        if !self.discord_id.is_empty() {
            size += 1u32 + ::buffa::types::string_encoded_len(&self.discord_id) as u32;
        }
        if self.account_created_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_created_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.account_modified_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_modified_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u32 + ::buffa::encoding::varint_len(inner_size as u64) as u32
                    + inner_size;
        }
        if self.promotion != 0i32 {
            size += 1u32 + ::buffa::types::int32_encoded_len(self.promotion) as u32;
        }
        if self.permissions != 0i64 {
            size += 1u32 + ::buffa::types::int64_encoded_len(self.permissions) as u32;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u32;
        size
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::bytes::BufMut,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.id != 0i64 {
            ::buffa::encoding::Tag::new(1u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_int64(self.id, buf);
        }
        if !self.username.is_empty() {
            ::buffa::encoding::Tag::new(
                    2u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.username, buf);
        }
        if !self.first_name.is_empty() {
            ::buffa::encoding::Tag::new(
                    3u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.first_name, buf);
        }
        if let Some(ref v) = self.last_name {
            ::buffa::encoding::Tag::new(
                    4u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(v, buf);
        }
        if !self.discord_id.is_empty() {
            ::buffa::encoding::Tag::new(
                    5u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::types::encode_string(&self.discord_id, buf);
        }
        if self.account_created_date.is_set() {
            ::buffa::encoding::Tag::new(
                    6u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
            self.account_created_date.write_to(__cache, buf);
        }
        if self.account_modified_date.is_set() {
            ::buffa::encoding::Tag::new(
                    7u32,
                    ::buffa::encoding::WireType::LengthDelimited,
                )
                .encode(buf);
            ::buffa::encoding::encode_varint(__cache.consume_next() as u64, buf);
            self.account_modified_date.write_to(__cache, buf);
        }
        if self.promotion != 0i32 {
            ::buffa::encoding::Tag::new(8u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_int32(self.promotion, buf);
        }
        if self.permissions != 0i64 {
            ::buffa::encoding::Tag::new(9u32, ::buffa::encoding::WireType::Varint)
                .encode(buf);
            ::buffa::types::encode_int64(self.permissions, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        depth: u32,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 1u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.id = ::buffa::types::decode_int64(buf)?;
            }
            2u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 2u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.username, buf)?;
            }
            3u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 3u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.first_name, buf)?;
            }
            4u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 4u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(
                    self
                        .last_name
                        .get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            5u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 5u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::types::merge_string(&mut self.discord_id, buf)?;
            }
            6u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 6u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::Message::merge_length_delimited(
                    self.account_created_date.get_or_insert_default(),
                    buf,
                    depth,
                )?;
            }
            7u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::LengthDelimited {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 7u32,
                        expected: 2u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                ::buffa::Message::merge_length_delimited(
                    self.account_modified_date.get_or_insert_default(),
                    buf,
                    depth,
                )?;
            }
            8u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 8u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.promotion = ::buffa::types::decode_int32(buf)?;
            }
            9u32 => {
                if tag.wire_type() != ::buffa::encoding::WireType::Varint {
                    return ::core::result::Result::Err(::buffa::DecodeError::WireTypeMismatch {
                        field_number: 9u32,
                        expected: 0u8,
                        actual: tag.wire_type() as u8,
                    });
                }
                self.permissions = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, depth)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.id = 0i64;
        self.username.clear();
        self.first_name.clear();
        self.last_name = ::core::option::Option::None;
        self.discord_id.clear();
        self.account_created_date = ::buffa::MessageField::none();
        self.account_modified_date = ::buffa::MessageField::none();
        self.promotion = 0i32;
        self.permissions = 0i64;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for DBUser {
    const PROTO_FQN: &'static str = "auth.v2.DBUser";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for DBUser {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __DB_USER_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/auth.v2.DBUser",
    to_json: ::buffa::type_registry::any_to_json::<DBUser>,
    from_json: ::buffa::type_registry::any_from_json::<DBUser>,
    is_wkt: false,
};
