// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/auth_data.proto

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(i32)]
pub enum Attribute {
    ATTRIBUTE_UNSPECIFIED = 0i32,
    ATTRIBUTE_CUBE = 1i32,
    ATTRIBUTE_MPSI = 2i32,
    ATTRIBUTE_PCSI = 3i32,
    ATTRIBUTE_BCPST = 4i32,
}
impl Attribute {
    ///Idiomatic alias for [`Self::ATTRIBUTE_UNSPECIFIED`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Unspecified: Self = Self::ATTRIBUTE_UNSPECIFIED;
    ///Idiomatic alias for [`Self::ATTRIBUTE_CUBE`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Cube: Self = Self::ATTRIBUTE_CUBE;
    ///Idiomatic alias for [`Self::ATTRIBUTE_MPSI`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Mpsi: Self = Self::ATTRIBUTE_MPSI;
    ///Idiomatic alias for [`Self::ATTRIBUTE_PCSI`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Pcsi: Self = Self::ATTRIBUTE_PCSI;
    ///Idiomatic alias for [`Self::ATTRIBUTE_BCPST`]; `Debug` prints the variant name.
    #[allow(non_upper_case_globals)]
    pub const Bcpst: Self = Self::ATTRIBUTE_BCPST;
}
impl ::core::default::Default for Attribute {
    fn default() -> Self {
        Self::ATTRIBUTE_UNSPECIFIED
    }
}
impl ::serde::Serialize for Attribute {
    fn serialize<S: ::serde::Serializer>(
        &self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        s.serialize_str(::buffa::Enumeration::proto_name(self))
    }
}
impl<'de> ::serde::Deserialize<'de> for Attribute {
    fn deserialize<D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        struct _V;
        impl ::serde::de::Visitor<'_> for _V {
            type Value = Attribute;
            fn expecting(
                &self,
                f: &mut ::core::fmt::Formatter<'_>,
            ) -> ::core::fmt::Result {
                f.write_str(
                    concat!("a string, integer, or null for ", stringify!(Attribute)),
                )
            }
            fn visit_str<E: ::serde::de::Error>(
                self,
                v: &str,
            ) -> ::core::result::Result<Attribute, E> {
                <Attribute as ::buffa::Enumeration>::from_proto_name(v)
                    .ok_or_else(|| { ::serde::de::Error::unknown_variant(v, &[]) })
            }
            fn visit_i64<E: ::serde::de::Error>(
                self,
                v: i64,
            ) -> ::core::result::Result<Attribute, E> {
                let v32 = i32::try_from(v)
                    .map_err(|_| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("enum value {v} out of i32 range"),
                        )
                    })?;
                <Attribute as ::buffa::Enumeration>::from_i32(v32)
                    .ok_or_else(|| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("unknown enum value {v32}"),
                        )
                    })
            }
            fn visit_u64<E: ::serde::de::Error>(
                self,
                v: u64,
            ) -> ::core::result::Result<Attribute, E> {
                let v32 = i32::try_from(v)
                    .map_err(|_| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("enum value {v} out of i32 range"),
                        )
                    })?;
                <Attribute as ::buffa::Enumeration>::from_i32(v32)
                    .ok_or_else(|| {
                        ::serde::de::Error::custom(
                            ::buffa::alloc::format!("unknown enum value {v32}"),
                        )
                    })
            }
            fn visit_unit<E: ::serde::de::Error>(
                self,
            ) -> ::core::result::Result<Attribute, E> {
                ::core::result::Result::Ok(::core::default::Default::default())
            }
        }
        d.deserialize_any(_V)
    }
}
impl ::buffa::json_helpers::ProtoElemJson for Attribute {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
impl ::buffa::Enumeration for Attribute {
    fn from_i32(value: i32) -> ::core::option::Option<Self> {
        match value {
            0i32 => ::core::option::Option::Some(Self::ATTRIBUTE_UNSPECIFIED),
            1i32 => ::core::option::Option::Some(Self::ATTRIBUTE_CUBE),
            2i32 => ::core::option::Option::Some(Self::ATTRIBUTE_MPSI),
            3i32 => ::core::option::Option::Some(Self::ATTRIBUTE_PCSI),
            4i32 => ::core::option::Option::Some(Self::ATTRIBUTE_BCPST),
            _ => ::core::option::Option::None,
        }
    }
    fn to_i32(&self) -> i32 {
        *self as i32
    }
    fn proto_name(&self) -> &'static str {
        match self {
            Self::ATTRIBUTE_UNSPECIFIED => "ATTRIBUTE_UNSPECIFIED",
            Self::ATTRIBUTE_CUBE => "ATTRIBUTE_CUBE",
            Self::ATTRIBUTE_MPSI => "ATTRIBUTE_MPSI",
            Self::ATTRIBUTE_PCSI => "ATTRIBUTE_PCSI",
            Self::ATTRIBUTE_BCPST => "ATTRIBUTE_BCPST",
        }
    }
    fn from_proto_name(name: &str) -> ::core::option::Option<Self> {
        match name {
            "ATTRIBUTE_UNSPECIFIED" => {
                ::core::option::Option::Some(Self::ATTRIBUTE_UNSPECIFIED)
            }
            "ATTRIBUTE_CUBE" => ::core::option::Option::Some(Self::ATTRIBUTE_CUBE),
            "ATTRIBUTE_MPSI" => ::core::option::Option::Some(Self::ATTRIBUTE_MPSI),
            "ATTRIBUTE_PCSI" => ::core::option::Option::Some(Self::ATTRIBUTE_PCSI),
            "ATTRIBUTE_BCPST" => ::core::option::Option::Some(Self::ATTRIBUTE_BCPST),
            _ => ::core::option::Option::None,
        }
    }
    fn values() -> &'static [Self] {
        &[
            Self::ATTRIBUTE_UNSPECIFIED,
            Self::ATTRIBUTE_CUBE,
            Self::ATTRIBUTE_MPSI,
            Self::ATTRIBUTE_PCSI,
            Self::ATTRIBUTE_BCPST,
        ]
    }
}
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct DBUser {
    /// Field 1: `id`
    #[serde(
        rename = "id",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub id: i64,
    /// Field 2: `username`
    #[serde(
        rename = "username",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub username: ::buffa::alloc::string::String,
    /// Field 3: `first_name`
    #[serde(
        rename = "firstName",
        alias = "first_name",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub first_name: ::buffa::alloc::string::String,
    /// Field 4: `last_name`
    #[serde(
        rename = "lastName",
        alias = "last_name",
        skip_serializing_if = "::core::option::Option::is_none"
    )]
    pub last_name: ::core::option::Option<::buffa::alloc::string::String>,
    /// Field 5: `discord_id`
    #[serde(
        rename = "discordId",
        alias = "discord_id",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub discord_id: ::buffa::alloc::string::String,
    /// Field 6: `account_created_date`
    #[serde(
        rename = "accountCreatedDate",
        alias = "account_created_date",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub account_created_date: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
    >,
    /// Field 7: `account_modified_date`
    #[serde(
        rename = "accountModifiedDate",
        alias = "account_modified_date",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub account_modified_date: ::buffa::MessageField<
        ::buffa_types::google::protobuf::Timestamp,
        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
    >,
    /// Field 8: `promotion`
    #[serde(
        rename = "promotion",
        with = "::buffa::json_helpers::int32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i32"
    )]
    pub promotion: i32,
    /// Field 9: `permissions`
    #[serde(
        rename = "permissions",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub permissions: i64,
    /// Field 10: `is_api`
    #[serde(
        rename = "isApi",
        alias = "is_api",
        with = "::buffa::json_helpers::proto_bool",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_false"
    )]
    pub is_api: bool,
    /// Field 11: `attributes`
    #[serde(
        rename = "attributes",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub attributes: i64,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for DBUser {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("DBUser")
            .field("id", &self.id)
            .field("username", &self.username)
            .field("first_name", &self.first_name)
            .field("last_name", &self.last_name)
            .field("discord_id", &self.discord_id)
            .field("account_created_date", &self.account_created_date)
            .field("account_modified_date", &self.account_modified_date)
            .field("promotion", &self.promotion)
            .field("permissions", &self.permissions)
            .field("is_api", &self.is_api)
            .field("attributes", &self.attributes)
            .finish()
    }
}
impl DBUser {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.DBUser";
}
impl DBUser {
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::last_name`] to `Some(value)`, consuming and returning `self`.
    pub fn with_last_name(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.last_name = Some(value.into());
        self
    }
}
::buffa::impl_default_instance!(DBUser);
impl ::buffa_descriptor::reflect::ReflectMessage for DBUser {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        __buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        __buffa::reflect::descriptor_pool()
    }
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            1u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.id),
            2u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.username),
            3u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.first_name),
            4u32 => {
                ::buffa_descriptor::reflect::ValueRef::String(
                    self.last_name.as_deref().unwrap_or(""),
                )
            }
            5u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.discord_id),
            6u32 => {
                ::buffa_descriptor::reflect::ValueRef::Message(
                    ::buffa_descriptor::reflect::Reflectable::reflect(
                        &*self.account_created_date,
                    ),
                )
            }
            7u32 => {
                ::buffa_descriptor::reflect::ValueRef::Message(
                    ::buffa_descriptor::reflect::Reflectable::reflect(
                        &*self.account_modified_date,
                    ),
                )
            }
            8u32 => ::buffa_descriptor::reflect::ValueRef::I32(self.promotion),
            9u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.permissions),
            10u32 => ::buffa_descriptor::reflect::ValueRef::Bool(self.is_api),
            11u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.attributes),
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this message's reflect get()",
                    field.number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            1u32 => self.id != 0,
            2u32 => !self.username.is_empty(),
            3u32 => !self.first_name.is_empty(),
            4u32 => self.last_name.is_some(),
            5u32 => !self.discord_id.is_empty(),
            6u32 => self.account_created_date.is_set(),
            7u32 => self.account_modified_date.is_set(),
            8u32 => self.promotion != 0,
            9u32 => self.permissions != 0,
            10u32 => self.is_api,
            11u32 => self.attributes != 0,
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        ::buffa_descriptor::reflect::DynamicMessage::from_message(
            self,
            ::buffa::alloc::sync::Arc::clone(__buffa::reflect::descriptor_pool()),
            Self::__buffa_reflect_message_index(),
        )
    }
}
impl ::buffa_descriptor::reflect::ReflectElement for DBUser {
    #[inline]
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl DBUser {
    /// Memoized `MessageIndex` for this message type, resolved once
    /// against the package's embedded descriptor pool.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                __buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated message is registered in the embedded descriptor pool",
                    )
            })
    }
}
impl ::buffa_descriptor::reflect::Reflectable for DBUser {
    /// Vtable-mode reflective handle: borrows `self` directly. No
    /// encode/decode round-trip and no allocation — the reflective
    /// accessors read this message's fields in place.
    #[inline]
    fn reflect(&self) -> ::buffa_descriptor::reflect::ReflectCow<'_> {
        ::buffa_descriptor::reflect::ReflectCow::Borrowed(self)
    }
}
impl ::buffa::MessageName for DBUser {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "DBUser";
    const FULL_NAME: &'static str = "auth.v2.DBUser";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.DBUser";
}
impl ::buffa::Message for DBUser {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.id != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.id) as u64;
        }
        if !self.username.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.username) as u64;
        }
        if !self.first_name.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.first_name) as u64;
        }
        if let Some(ref v) = self.last_name {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if !self.discord_id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.discord_id) as u64;
        }
        if self.account_created_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_created_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.account_modified_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_modified_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.promotion != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.promotion) as u64;
        }
        if self.permissions != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.permissions) as u64;
        }
        if self.is_api {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if self.attributes != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.attributes) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.id != 0i64 {
            ::buffa::types::put_int64_field(1u32, self.id, buf);
        }
        if !self.username.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.username, buf);
        }
        if !self.first_name.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.first_name, buf);
        }
        if let Some(ref v) = self.last_name {
            ::buffa::types::put_string_field(4u32, v, buf);
        }
        if !self.discord_id.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.discord_id, buf);
        }
        if self.account_created_date.is_set() {
            ::buffa::types::put_len_delimited_header(
                6u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.account_created_date.write_to(__cache, buf);
        }
        if self.account_modified_date.is_set() {
            ::buffa::types::put_len_delimited_header(
                7u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.account_modified_date.write_to(__cache, buf);
        }
        if self.promotion != 0i32 {
            ::buffa::types::put_int32_field(8u32, self.promotion, buf);
        }
        if self.permissions != 0i64 {
            ::buffa::types::put_int64_field(9u32, self.permissions, buf);
        }
        if self.is_api {
            ::buffa::types::put_bool_field(10u32, self.is_api, buf);
        }
        if self.attributes != 0i64 {
            ::buffa::types::put_int64_field(11u32, self.attributes, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.id = ::buffa::types::decode_int64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.username, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.first_name, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    self
                        .last_name
                        .get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.discord_id, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.account_created_date.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.account_modified_date.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.promotion = ::buffa::types::decode_int32(buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.permissions = ::buffa::types::decode_int64(buf)?;
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.is_api = ::buffa::types::decode_bool(buf)?;
            }
            11u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.attributes = ::buffa::types::decode_int64(buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.id = 0i64;
        self.username.clear();
        self.first_name.clear();
        self.last_name = ::core::option::Option::None;
        self.discord_id.clear();
        self.account_created_date = ::buffa::MessageField::none();
        self.account_modified_date = ::buffa::MessageField::none();
        self.promotion = 0i32;
        self.permissions = 0i64;
        self.is_api = false;
        self.attributes = 0i64;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for DBUser {
    const PROTO_FQN: &'static str = "auth.v2.DBUser";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for DBUser {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __DB_USER_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/auth.v2.DBUser",
    to_json: ::buffa::type_registry::any_to_json::<DBUser>,
    from_json: ::buffa::type_registry::any_from_json::<DBUser>,
    is_wkt: false,
};
