// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/auth_data.proto

#[derive(Clone, Debug, Default)]
pub struct DBUserView<'a> {
    /// Field 1: `id`
    pub id: i64,
    /// Field 2: `username`
    pub username: &'a str,
    /// Field 3: `first_name`
    pub first_name: &'a str,
    /// Field 4: `last_name`
    pub last_name: ::core::option::Option<&'a str>,
    /// Field 5: `discord_id`
    pub discord_id: &'a str,
    /// Field 6: `account_created_date`
    pub account_created_date: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 7: `account_modified_date`
    pub account_modified_date: ::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'a>,
    >,
    /// Field 8: `promotion`
    pub promotion: i32,
    /// Field 9: `permissions`
    pub permissions: i64,
    pub __buffa_unknown_fields: ::buffa::UnknownFieldsView<'a>,
}
impl<'a> ::buffa::MessageView<'a> for DBUserView<'a> {
    type Owned = super::super::DBUser;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.id = ::buffa::types::decode_int64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.username = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.first_name = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.last_name = Some(::buffa::types::borrow_str(&mut cur)?);
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.discord_id = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.account_created_date.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.account_created_date = ::buffa::MessageFieldView::set(
                            <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.account_modified_date.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.account_modified_date = ::buffa::MessageFieldView::set(
                            <::buffa_types::google::protobuf::__buffa::view::TimestampView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.promotion = ::buffa::types::decode_int32(&mut cur)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.permissions = ::buffa::types::decode_int64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
                let span_len = before_tag.len() - cur.len();
                view.__buffa_unknown_fields.push_record(before_tag, span_len, ctx)?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::DBUser, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::DBUser, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::DBUser {
            id: self.id,
            username: self.username.to_string(),
            first_name: self.first_name.to_string(),
            last_name: self.last_name.map(|s| s.to_string()),
            discord_id: self.discord_id.to_string(),
            account_created_date: match self.account_created_date.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            account_modified_date: match self.account_modified_date.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        ::buffa_types::google::protobuf::Timestamp,
                        ::buffa::Inline<::buffa_types::google::protobuf::Timestamp>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            promotion: self.promotion,
            permissions: self.permissions,
            __buffa_unknown_fields: self.__buffa_unknown_fields.to_owned()?.into(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for DBUserView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.id != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.id) as u64;
        }
        if !self.username.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.username) as u64;
        }
        if !self.first_name.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.first_name) as u64;
        }
        if let Some(ref v) = self.last_name {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if !self.discord_id.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.discord_id) as u64;
        }
        if self.account_created_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_created_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.account_modified_date.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.account_modified_date.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        if self.promotion != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.promotion) as u64;
        }
        if self.permissions != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.permissions) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.id != 0i64 {
            ::buffa::types::put_int64_field(1u32, self.id, buf);
        }
        if !self.username.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.username, buf);
        }
        if !self.first_name.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.first_name, buf);
        }
        if let Some(ref v) = self.last_name {
            ::buffa::types::put_string_field(4u32, v, buf);
        }
        if !self.discord_id.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.discord_id, buf);
        }
        if self.account_created_date.is_set() {
            ::buffa::types::put_len_delimited_header(
                6u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.account_created_date.write_to(__cache, buf);
        }
        if self.account_modified_date.is_set() {
            ::buffa::types::put_len_delimited_header(
                7u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.account_modified_date.write_to(__cache, buf);
        }
        if self.promotion != 0i32 {
            ::buffa::types::put_int32_field(8u32, self.promotion, buf);
        }
        if self.permissions != 0i64 {
            ::buffa::types::put_int64_field(9u32, self.permissions, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
}
/// Serializes this view as protobuf JSON.
///
/// Implicit-presence fields with default values are omitted, `required`
/// fields are always emitted, explicit-presence (`optional`) fields are
/// emitted only when set, bytes fields are base64-encoded, and enum
/// values are their proto name strings.
///
/// This impl uses `serialize_map(None)` because the number of emitted
/// fields depends on default-omission rules; serializers that require
/// known map lengths (e.g. `bincode`) will return a runtime error.
/// Use the owned message type for those formats.
impl<'__a> ::serde::Serialize for DBUserView<'__a> {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        use ::serde::ser::SerializeMap as _;
        let mut __map = __s.serialize_map(::core::option::Option::None)?;
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.id) {
            __map.serialize_entry("id", &::buffa::json_helpers::ProtoJson(&self.id))?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.username) {
            __map.serialize_entry("username", self.username)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.first_name) {
            __map.serialize_entry("firstName", self.first_name)?;
        }
        if let ::core::option::Option::Some(__v) = self.last_name {
            __map.serialize_entry("lastName", __v)?;
        }
        if !::buffa::json_helpers::skip_if::is_empty_str(self.discord_id) {
            __map.serialize_entry("discordId", self.discord_id)?;
        }
        {
            if let ::core::option::Option::Some(__v) = self
                .account_created_date
                .as_option()
            {
                __map.serialize_entry("accountCreatedDate", __v)?;
            }
        }
        {
            if let ::core::option::Option::Some(__v) = self
                .account_modified_date
                .as_option()
            {
                __map.serialize_entry("accountModifiedDate", __v)?;
            }
        }
        if !::buffa::json_helpers::skip_if::is_zero_i32(&self.promotion) {
            __map
                .serialize_entry(
                    "promotion",
                    &::buffa::json_helpers::ProtoJson(&self.promotion),
                )?;
        }
        if !::buffa::json_helpers::skip_if::is_zero_i64(&self.permissions) {
            __map
                .serialize_entry(
                    "permissions",
                    &::buffa::json_helpers::ProtoJson(&self.permissions),
                )?;
        }
        __map.end()
    }
}
impl<'a> ::buffa::MessageName for DBUserView<'a> {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "DBUser";
    const FULL_NAME: &'static str = "auth.v2.DBUser";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.DBUser";
}
::buffa::impl_default_view_instance!(DBUserView);
::buffa::impl_view_reborrow!(DBUserView);
/** Self-contained, `'static` owned view of a `DBUser` message.

 Wraps [`::buffa::OwnedView`]`<`[`DBUserView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`DBUserView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct DBUserOwnedView(::buffa::OwnedView<DBUserView<'static>>);
impl DBUserOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(DBUserOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            DBUserOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::DBUser,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(DBUserOwnedView(::buffa::OwnedView::from_owned(msg)?))
    }
    /// Borrow the full [`DBUserView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &DBUserView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::DBUser {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `id`
    #[must_use]
    pub fn id(&self) -> i64 {
        self.0.reborrow().id
    }
    /// Field 2: `username`
    #[must_use]
    pub fn username(&self) -> &'_ str {
        self.0.reborrow().username
    }
    /// Field 3: `first_name`
    #[must_use]
    pub fn first_name(&self) -> &'_ str {
        self.0.reborrow().first_name
    }
    /// Field 4: `last_name`
    #[must_use]
    pub fn last_name(&self) -> ::core::option::Option<&'_ str> {
        self.0.reborrow().last_name
    }
    /// Field 5: `discord_id`
    #[must_use]
    pub fn discord_id(&self) -> &'_ str {
        self.0.reborrow().discord_id
    }
    /// Field 6: `account_created_date`
    #[must_use]
    pub fn account_created_date(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().account_created_date
    }
    /// Field 7: `account_modified_date`
    #[must_use]
    pub fn account_modified_date(
        &self,
    ) -> &::buffa::MessageFieldView<
        ::buffa_types::google::protobuf::__buffa::view::TimestampView<'_>,
    > {
        &self.0.reborrow().account_modified_date
    }
    /// Field 8: `promotion`
    #[must_use]
    pub fn promotion(&self) -> i32 {
        self.0.reborrow().promotion
    }
    /// Field 9: `permissions`
    #[must_use]
    pub fn permissions(&self) -> i64 {
        self.0.reborrow().permissions
    }
}
impl ::core::convert::From<::buffa::OwnedView<DBUserView<'static>>> for DBUserOwnedView {
    fn from(inner: ::buffa::OwnedView<DBUserView<'static>>) -> Self {
        DBUserOwnedView(inner)
    }
}
impl ::core::convert::From<DBUserOwnedView> for ::buffa::OwnedView<DBUserView<'static>> {
    fn from(wrapper: DBUserOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<DBUserView<'static>>>
for DBUserOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<DBUserView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::DBUser {
    type View<'a> = DBUserView<'a>;
    type ViewHandle = DBUserOwnedView;
}
impl ::serde::Serialize for DBUserOwnedView {
    fn serialize<__S: ::serde::Serializer>(
        &self,
        __s: __S,
    ) -> ::core::result::Result<__S::Ok, __S::Error> {
        ::serde::Serialize::serialize(&self.0, __s)
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectMessage for DBUserView<'a> {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        super::super::__buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        super::super::__buffa::reflect::descriptor_pool()
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            1u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.id),
            2u32 => ::buffa_descriptor::reflect::ValueRef::String(self.username),
            3u32 => ::buffa_descriptor::reflect::ValueRef::String(self.first_name),
            4u32 => {
                ::buffa_descriptor::reflect::ValueRef::String(
                    self.last_name.unwrap_or(""),
                )
            }
            5u32 => ::buffa_descriptor::reflect::ValueRef::String(self.discord_id),
            6u32 => {
                ::buffa_descriptor::reflect::ValueRef::Message(
                    ::buffa_descriptor::reflect::ReflectCow::Borrowed(
                        &*self.account_created_date,
                    ),
                )
            }
            7u32 => {
                ::buffa_descriptor::reflect::ValueRef::Message(
                    ::buffa_descriptor::reflect::ReflectCow::Borrowed(
                        &*self.account_modified_date,
                    ),
                )
            }
            8u32 => ::buffa_descriptor::reflect::ValueRef::I32(self.promotion),
            9u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.permissions),
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this view's reflect get()", field
                    .number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            1u32 => self.id != 0,
            2u32 => !self.username.is_empty(),
            3u32 => !self.first_name.is_empty(),
            4u32 => self.last_name.is_some(),
            5u32 => !self.discord_id.is_empty(),
            6u32 => self.account_created_date.is_set(),
            7u32 => self.account_modified_date.is_set(),
            8u32 => self.promotion != 0,
            9u32 => self.permissions != 0,
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        let bytes = ::buffa::ViewEncode::encode_to_vec(self);
        let options = ::buffa::DecodeOptions::new()
            .with_element_memory_limit(
                bytes
                    .len()
                    .saturating_mul(128)
                    .max(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT),
            )
            .with_unknown_field_limit(
                bytes.len().max(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT),
            );
        ::buffa_descriptor::reflect::DynamicMessage::decode_with_options(
                ::buffa::alloc::sync::Arc::clone(
                    super::super::__buffa::reflect::descriptor_pool(),
                ),
                Self::__buffa_reflect_message_index(),
                &bytes,
                &options,
            )
            .expect("view re-encodes to bytes decodable against its own descriptor")
    }
}
impl<'a> ::buffa_descriptor::reflect::ReflectElement for DBUserView<'a> {
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl<'a> DBUserView<'a> {
    /// Memoized `MessageIndex` for this view's message type, resolved
    /// once against the package's embedded descriptor pool. An inherent
    /// associated fn (not a free fn) so sibling views in the same module
    /// do not collide.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                super::super::__buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated view type is registered in the embedded descriptor pool",
                    )
            })
    }
}
