// @generated by buffa-codegen. DO NOT EDIT.

include!("auth.v1.greet.rs");
include!("auth.v1.permissions.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("auth.v1.greet.__view.rs");
        include!("auth.v1.permissions.__view.rs");
    }
    pub mod ext {
        #[allow(unused_imports)]
        use super::*;
        include!("auth.v1.permissions.__ext.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__GREET_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GREET_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__PERMISSIONS_JSON_ANY);
        reg.register_json_any(super::__DELETE_USER_REQUEST_JSON_ANY);
        reg.register_json_any(super::__DELETE_USER_RESPONSE_JSON_ANY);
        reg.register_json_ext(super::__buffa::ext::__PERMISSION_LEVEL_JSON_EXT);
        reg.register_json_ext(super::__buffa::ext::__PERMISSION_LEVEL_SERVICE_JSON_EXT);
    }
}
#[doc(inline)]
pub use self::__buffa::view::GreetRequestView;
#[doc(inline)]
pub use self::__buffa::view::GreetRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GreetResponseView;
#[doc(inline)]
pub use self::__buffa::view::GreetResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::view::PermissionsView;
#[doc(inline)]
pub use self::__buffa::view::PermissionsOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DeleteUserRequestView;
#[doc(inline)]
pub use self::__buffa::view::DeleteUserRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::DeleteUserResponseView;
#[doc(inline)]
pub use self::__buffa::view::DeleteUserResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::ext::PERMISSION_LEVEL;
#[doc(inline)]
pub use self::__buffa::ext::PERMISSION_LEVEL_SERVICE;
#[doc(inline)]
pub use self::__buffa::register_types;
