// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/permissions.proto

///Extension `permission_level` on `.google.protobuf.MethodOptions` (field 50801).
pub const PERMISSION_LEVEL: ::buffa::Extension<
    ::buffa::extension::codecs::MessageCodec<super::super::Permissions>,
> = ::buffa::Extension::new(50801u32, "google.protobuf.MethodOptions");
#[doc(hidden)]
pub const __PERMISSION_LEVEL_JSON_EXT: ::buffa::type_registry::JsonExtEntry = ::buffa::type_registry::JsonExtEntry {
    number: 50801u32,
    full_name: "auth.v2.permission_level",
    extendee: "google.protobuf.MethodOptions",
    to_json: ::buffa::extension_registry::helpers::message_to_json::<
        super::super::Permissions,
    >,
    from_json: ::buffa::extension_registry::helpers::message_from_json::<
        super::super::Permissions,
    >,
};
///Extension `permission_level_service` on `.google.protobuf.ServiceOptions` (field 50802).
pub const PERMISSION_LEVEL_SERVICE: ::buffa::Extension<
    ::buffa::extension::codecs::MessageCodec<super::super::Permissions>,
> = ::buffa::Extension::new(50802u32, "google.protobuf.ServiceOptions");
#[doc(hidden)]
pub const __PERMISSION_LEVEL_SERVICE_JSON_EXT: ::buffa::type_registry::JsonExtEntry = ::buffa::type_registry::JsonExtEntry {
    number: 50802u32,
    full_name: "auth.v2.permission_level_service",
    extendee: "google.protobuf.ServiceOptions",
    to_json: ::buffa::extension_registry::helpers::message_to_json::<
        super::super::Permissions,
    >,
    from_json: ::buffa::extension_registry::helpers::message_from_json::<
        super::super::Permissions,
    >,
};
