// @generated by buffa-codegen. DO NOT EDIT.
// source: auth/v2/jwt.proto

#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct SmallData {
    /// Field 1: `user_id`
    #[serde(
        rename = "userId",
        alias = "user_id",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub user_id: i64,
    /// Field 2: `username`
    #[serde(
        rename = "username",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub username: ::buffa::alloc::string::String,
    /// Field 3: `first_name`
    #[serde(
        rename = "firstName",
        alias = "first_name",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub first_name: ::buffa::alloc::string::String,
    /// Field 4: `last_name`
    #[serde(
        rename = "lastName",
        alias = "last_name",
        skip_serializing_if = "::core::option::Option::is_none"
    )]
    pub last_name: ::core::option::Option<::buffa::alloc::string::String>,
    /// Field 5: `permissions`
    #[serde(
        rename = "permissions",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub permissions: i64,
    /// Field 6: `promotion`
    #[serde(
        rename = "promotion",
        with = "::buffa::json_helpers::int32",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i32"
    )]
    pub promotion: i32,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for SmallData {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SmallData")
            .field("user_id", &self.user_id)
            .field("username", &self.username)
            .field("first_name", &self.first_name)
            .field("last_name", &self.last_name)
            .field("permissions", &self.permissions)
            .field("promotion", &self.promotion)
            .finish()
    }
}
impl SmallData {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.SmallData";
}
impl SmallData {
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::last_name`] to `Some(value)`, consuming and returning `self`.
    pub fn with_last_name(
        mut self,
        value: impl Into<::buffa::alloc::string::String>,
    ) -> Self {
        self.last_name = Some(value.into());
        self
    }
}
::buffa::impl_default_instance!(SmallData);
impl ::buffa_descriptor::reflect::ReflectMessage for SmallData {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        __buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        __buffa::reflect::descriptor_pool()
    }
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            1u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.user_id),
            2u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.username),
            3u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.first_name),
            4u32 => {
                ::buffa_descriptor::reflect::ValueRef::String(
                    self.last_name.as_deref().unwrap_or(""),
                )
            }
            5u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.permissions),
            6u32 => ::buffa_descriptor::reflect::ValueRef::I32(self.promotion),
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this message's reflect get()",
                    field.number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            1u32 => self.user_id != 0,
            2u32 => !self.username.is_empty(),
            3u32 => !self.first_name.is_empty(),
            4u32 => self.last_name.is_some(),
            5u32 => self.permissions != 0,
            6u32 => self.promotion != 0,
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        ::buffa_descriptor::reflect::DynamicMessage::from_message(
            self,
            ::buffa::alloc::sync::Arc::clone(__buffa::reflect::descriptor_pool()),
            Self::__buffa_reflect_message_index(),
        )
    }
}
impl ::buffa_descriptor::reflect::ReflectElement for SmallData {
    #[inline]
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl SmallData {
    /// Memoized `MessageIndex` for this message type, resolved once
    /// against the package's embedded descriptor pool.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                __buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated message is registered in the embedded descriptor pool",
                    )
            })
    }
}
impl ::buffa_descriptor::reflect::Reflectable for SmallData {
    /// Vtable-mode reflective handle: borrows `self` directly. No
    /// encode/decode round-trip and no allocation — the reflective
    /// accessors read this message's fields in place.
    #[inline]
    fn reflect(&self) -> ::buffa_descriptor::reflect::ReflectCow<'_> {
        ::buffa_descriptor::reflect::ReflectCow::Borrowed(self)
    }
}
impl ::buffa::MessageName for SmallData {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "SmallData";
    const FULL_NAME: &'static str = "auth.v2.SmallData";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.SmallData";
}
impl ::buffa::Message for SmallData {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.user_id != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.user_id) as u64;
        }
        if !self.username.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.username) as u64;
        }
        if !self.first_name.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.first_name) as u64;
        }
        if let Some(ref v) = self.last_name {
            size += 1u64 + ::buffa::types::string_encoded_len(v) as u64;
        }
        if self.permissions != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.permissions) as u64;
        }
        if self.promotion != 0i32 {
            size += 1u64 + ::buffa::types::int32_encoded_len(self.promotion) as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.user_id != 0i64 {
            ::buffa::types::put_int64_field(1u32, self.user_id, buf);
        }
        if !self.username.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.username, buf);
        }
        if !self.first_name.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.first_name, buf);
        }
        if let Some(ref v) = self.last_name {
            ::buffa::types::put_string_field(4u32, v, buf);
        }
        if self.permissions != 0i64 {
            ::buffa::types::put_int64_field(5u32, self.permissions, buf);
        }
        if self.promotion != 0i32 {
            ::buffa::types::put_int32_field(6u32, self.promotion, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.user_id = ::buffa::types::decode_int64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.username, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.first_name, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    self
                        .last_name
                        .get_or_insert_with(::buffa::alloc::string::String::new),
                    buf,
                )?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.permissions = ::buffa::types::decode_int64(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.promotion = ::buffa::types::decode_int32(buf)?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.user_id = 0i64;
        self.username.clear();
        self.first_name.clear();
        self.last_name = ::core::option::Option::None;
        self.permissions = 0i64;
        self.promotion = 0i32;
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for SmallData {
    const PROTO_FQN: &'static str = "auth.v2.SmallData";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for SmallData {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __SMALL_DATA_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/auth.v2.SmallData",
    to_json: ::buffa::type_registry::any_to_json::<SmallData>,
    from_json: ::buffa::type_registry::any_from_json::<SmallData>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct JwtClaims {
    /// Issuer
    ///
    /// Field 1: `iss`
    #[serde(
        rename = "iss",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub iss: ::buffa::alloc::string::String,
    /// Subject
    ///
    /// Field 2: `sub`
    #[serde(
        rename = "sub",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub sub: ::buffa::alloc::string::String,
    /// Audience
    ///
    /// Field 3: `aud`
    #[serde(
        rename = "aud",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub aud: ::buffa::alloc::string::String,
    /// Expiration Time (Unix timestamp)
    ///
    /// Field 4: `exp`
    #[serde(
        rename = "exp",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub exp: i64,
    /// Not Before (Unix timestamp)
    ///
    /// Field 5: `nbf`
    #[serde(
        rename = "nbf",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub nbf: i64,
    /// Issued At (Unix timestamp)
    ///
    /// Field 6: `iat`
    #[serde(
        rename = "iat",
        with = "::buffa::json_helpers::int64",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_zero_i64"
    )]
    pub iat: i64,
    /// JWT ID
    ///
    /// Field 7: `jti`
    #[serde(
        rename = "jti",
        with = "::buffa::json_helpers::proto_string",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_empty_str"
    )]
    pub jti: ::buffa::alloc::string::String,
    /// Field 8: `temporary`
    #[serde(
        rename = "temporary",
        with = "::buffa::json_helpers::proto_bool",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_false"
    )]
    pub temporary: bool,
    /// Field 9: `temporary_recheck_after`
    #[serde(
        rename = "temporaryRecheckAfter",
        alias = "temporary_recheck_after",
        with = "::buffa::json_helpers::opt_int64",
        skip_serializing_if = "::core::option::Option::is_none"
    )]
    pub temporary_recheck_after: ::core::option::Option<i64>,
    /// Field 10: `data`
    #[serde(
        rename = "data",
        skip_serializing_if = "::buffa::json_helpers::skip_if::is_unset_message_field"
    )]
    pub data: ::buffa::MessageField<SmallData, ::buffa::Inline<SmallData>>,
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for JwtClaims {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("JwtClaims")
            .field("iss", &self.iss)
            .field("sub", &self.sub)
            .field("aud", &self.aud)
            .field("exp", &self.exp)
            .field("nbf", &self.nbf)
            .field("iat", &self.iat)
            .field("jti", &self.jti)
            .field("temporary", &self.temporary)
            .field("temporary_recheck_after", &self.temporary_recheck_after)
            .field("data", &self.data)
            .finish()
    }
}
impl JwtClaims {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.JwtClaims";
}
impl JwtClaims {
    #[must_use = "with_* setters return `self` by value; assign or chain the result"]
    #[inline]
    ///Sets [`Self::temporary_recheck_after`] to `Some(value)`, consuming and returning `self`.
    pub fn with_temporary_recheck_after(mut self, value: i64) -> Self {
        self.temporary_recheck_after = Some(value);
        self
    }
}
::buffa::impl_default_instance!(JwtClaims);
impl ::buffa_descriptor::reflect::ReflectMessage for JwtClaims {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        __buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        __buffa::reflect::descriptor_pool()
    }
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            1u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.iss),
            2u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.sub),
            3u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.aud),
            4u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.exp),
            5u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.nbf),
            6u32 => ::buffa_descriptor::reflect::ValueRef::I64(self.iat),
            7u32 => ::buffa_descriptor::reflect::ValueRef::String(&self.jti),
            8u32 => ::buffa_descriptor::reflect::ValueRef::Bool(self.temporary),
            9u32 => {
                ::buffa_descriptor::reflect::ValueRef::I64(
                    self.temporary_recheck_after.unwrap_or(0),
                )
            }
            10u32 => {
                ::buffa_descriptor::reflect::ValueRef::Message(
                    ::buffa_descriptor::reflect::Reflectable::reflect(&*self.data),
                )
            }
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this message's reflect get()",
                    field.number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            1u32 => !self.iss.is_empty(),
            2u32 => !self.sub.is_empty(),
            3u32 => !self.aud.is_empty(),
            4u32 => self.exp != 0,
            5u32 => self.nbf != 0,
            6u32 => self.iat != 0,
            7u32 => !self.jti.is_empty(),
            8u32 => self.temporary,
            9u32 => self.temporary_recheck_after.is_some(),
            10u32 => self.data.is_set(),
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        ::buffa_descriptor::reflect::DynamicMessage::from_message(
            self,
            ::buffa::alloc::sync::Arc::clone(__buffa::reflect::descriptor_pool()),
            Self::__buffa_reflect_message_index(),
        )
    }
}
impl ::buffa_descriptor::reflect::ReflectElement for JwtClaims {
    #[inline]
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl JwtClaims {
    /// Memoized `MessageIndex` for this message type, resolved once
    /// against the package's embedded descriptor pool.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                __buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated message is registered in the embedded descriptor pool",
                    )
            })
    }
}
impl ::buffa_descriptor::reflect::Reflectable for JwtClaims {
    /// Vtable-mode reflective handle: borrows `self` directly. No
    /// encode/decode round-trip and no allocation — the reflective
    /// accessors read this message's fields in place.
    #[inline]
    fn reflect(&self) -> ::buffa_descriptor::reflect::ReflectCow<'_> {
        ::buffa_descriptor::reflect::ReflectCow::Borrowed(self)
    }
}
impl ::buffa::MessageName for JwtClaims {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "JwtClaims";
    const FULL_NAME: &'static str = "auth.v2.JwtClaims";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.JwtClaims";
}
impl ::buffa::Message for JwtClaims {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.iss.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.iss) as u64;
        }
        if !self.sub.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.sub) as u64;
        }
        if !self.aud.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.aud) as u64;
        }
        if self.exp != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.exp) as u64;
        }
        if self.nbf != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.nbf) as u64;
        }
        if self.iat != 0i64 {
            size += 1u64 + ::buffa::types::int64_encoded_len(self.iat) as u64;
        }
        if !self.jti.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.jti) as u64;
        }
        if self.temporary {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        if let Some(v) = self.temporary_recheck_after {
            size += 1u64 + ::buffa::types::int64_encoded_len(v) as u64;
        }
        if self.data.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.data.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.iss.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.iss, buf);
        }
        if !self.sub.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.sub, buf);
        }
        if !self.aud.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.aud, buf);
        }
        if self.exp != 0i64 {
            ::buffa::types::put_int64_field(4u32, self.exp, buf);
        }
        if self.nbf != 0i64 {
            ::buffa::types::put_int64_field(5u32, self.nbf, buf);
        }
        if self.iat != 0i64 {
            ::buffa::types::put_int64_field(6u32, self.iat, buf);
        }
        if !self.jti.is_empty() {
            ::buffa::types::put_string_field(7u32, &self.jti, buf);
        }
        if self.temporary {
            ::buffa::types::put_bool_field(8u32, self.temporary, buf);
        }
        if let Some(v) = self.temporary_recheck_after {
            ::buffa::types::put_int64_field(9u32, v, buf);
        }
        if self.data.is_set() {
            ::buffa::types::put_len_delimited_header(
                10u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.data.write_to(__cache, buf);
        }
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.iss, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.sub, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.aud, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.exp = ::buffa::types::decode_int64(buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.nbf = ::buffa::types::decode_int64(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.iat = ::buffa::types::decode_int64(buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.jti, buf)?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.temporary = ::buffa::types::decode_bool(buf)?;
            }
            9u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.temporary_recheck_after = ::core::option::Option::Some(
                    ::buffa::types::decode_int64(buf)?,
                );
            }
            10u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.data.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.iss.clear();
        self.sub.clear();
        self.aud.clear();
        self.exp = 0i64;
        self.nbf = 0i64;
        self.iat = 0i64;
        self.jti.clear();
        self.temporary = false;
        self.temporary_recheck_after = ::core::option::Option::None;
        self.data = ::buffa::MessageField::none();
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for JwtClaims {
    const PROTO_FQN: &'static str = "auth.v2.JwtClaims";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for JwtClaims {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __JWT_CLAIMS_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/auth.v2.JwtClaims",
    to_json: ::buffa::type_registry::any_to_json::<JwtClaims>,
    from_json: ::buffa::type_registry::any_from_json::<JwtClaims>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct GetCSRFTokenRequest {
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for GetCSRFTokenRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("GetCSRFTokenRequest").finish()
    }
}
impl GetCSRFTokenRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.GetCSRFTokenRequest";
}
::buffa::impl_default_instance!(GetCSRFTokenRequest);
impl ::buffa_descriptor::reflect::ReflectMessage for GetCSRFTokenRequest {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        __buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        __buffa::reflect::descriptor_pool()
    }
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this message's reflect get()",
                    field.number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        ::buffa_descriptor::reflect::DynamicMessage::from_message(
            self,
            ::buffa::alloc::sync::Arc::clone(__buffa::reflect::descriptor_pool()),
            Self::__buffa_reflect_message_index(),
        )
    }
}
impl ::buffa_descriptor::reflect::ReflectElement for GetCSRFTokenRequest {
    #[inline]
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl GetCSRFTokenRequest {
    /// Memoized `MessageIndex` for this message type, resolved once
    /// against the package's embedded descriptor pool.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                __buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated message is registered in the embedded descriptor pool",
                    )
            })
    }
}
impl ::buffa_descriptor::reflect::Reflectable for GetCSRFTokenRequest {
    /// Vtable-mode reflective handle: borrows `self` directly. No
    /// encode/decode round-trip and no allocation — the reflective
    /// accessors read this message's fields in place.
    #[inline]
    fn reflect(&self) -> ::buffa_descriptor::reflect::ReflectCow<'_> {
        ::buffa_descriptor::reflect::ReflectCow::Borrowed(self)
    }
}
impl ::buffa::MessageName for GetCSRFTokenRequest {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "GetCSRFTokenRequest";
    const FULL_NAME: &'static str = "auth.v2.GetCSRFTokenRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.GetCSRFTokenRequest";
}
impl ::buffa::Message for GetCSRFTokenRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for GetCSRFTokenRequest {
    const PROTO_FQN: &'static str = "auth.v2.GetCSRFTokenRequest";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for GetCSRFTokenRequest {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GET_CSRF_TOKEN_REQUEST_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/auth.v2.GetCSRFTokenRequest",
    to_json: ::buffa::type_registry::any_to_json::<GetCSRFTokenRequest>,
    from_json: ::buffa::type_registry::any_from_json::<GetCSRFTokenRequest>,
    is_wkt: false,
};
#[derive(Clone, PartialEq, Default)]
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct GetCSRFTokenResponse {
    #[serde(skip)]
    #[doc(hidden)]
    pub __buffa_unknown_fields: ::buffa::UnknownFields,
}
impl ::core::fmt::Debug for GetCSRFTokenResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("GetCSRFTokenResponse").finish()
    }
}
impl GetCSRFTokenResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.GetCSRFTokenResponse";
}
::buffa::impl_default_instance!(GetCSRFTokenResponse);
impl ::buffa_descriptor::reflect::ReflectMessage for GetCSRFTokenResponse {
    fn message_descriptor(&self) -> &::buffa_descriptor::MessageDescriptor {
        __buffa::reflect::descriptor_pool()
            .message(Self::__buffa_reflect_message_index())
    }
    fn pool(&self) -> &::buffa::alloc::sync::Arc<::buffa_descriptor::DescriptorPool> {
        __buffa::reflect::descriptor_pool()
    }
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn get(
        &self,
        field: &::buffa_descriptor::FieldDescriptor,
    ) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match field.number() {
            _ => {
                ::core::debug_assert!(
                    false,
                    "field number {} is not a member of this message's reflect get()",
                    field.number(),
                );
                ::buffa_descriptor::reflect::ValueRef::Bool(false)
            }
        }
    }
    fn has(&self, field: &::buffa_descriptor::FieldDescriptor) -> bool {
        match field.number() {
            _ => false,
        }
    }
    fn for_each_set(
        &self,
        f: &mut dyn ::core::ops::FnMut(
            &::buffa_descriptor::FieldDescriptor,
            ::buffa_descriptor::reflect::ValueRef<'_>,
        ),
    ) {
        let md = ::buffa_descriptor::reflect::ReflectMessage::message_descriptor(self);
        for fd in md.fields() {
            if ::buffa_descriptor::reflect::ReflectMessage::has(self, fd) {
                f(fd, ::buffa_descriptor::reflect::ReflectMessage::get(self, fd));
            }
        }
    }
    fn to_dynamic(&self) -> ::buffa_descriptor::reflect::DynamicMessage {
        ::buffa_descriptor::reflect::DynamicMessage::from_message(
            self,
            ::buffa::alloc::sync::Arc::clone(__buffa::reflect::descriptor_pool()),
            Self::__buffa_reflect_message_index(),
        )
    }
}
impl ::buffa_descriptor::reflect::ReflectElement for GetCSRFTokenResponse {
    #[inline]
    fn as_value_ref(&self) -> ::buffa_descriptor::reflect::ValueRef<'_> {
        ::buffa_descriptor::reflect::ValueRef::Message(
            ::buffa_descriptor::reflect::ReflectCow::Borrowed(self),
        )
    }
}
impl GetCSRFTokenResponse {
    /// Memoized `MessageIndex` for this message type, resolved once
    /// against the package's embedded descriptor pool.
    #[doc(hidden)]
    fn __buffa_reflect_message_index() -> ::buffa_descriptor::MessageIndex {
        static IDX: ::std::sync::OnceLock<::buffa_descriptor::MessageIndex> = ::std::sync::OnceLock::new();
        *IDX
            .get_or_init(|| {
                __buffa::reflect::descriptor_pool()
                    .message_index(<Self as ::buffa::MessageName>::FULL_NAME)
                    .expect(
                        "generated message is registered in the embedded descriptor pool",
                    )
            })
    }
}
impl ::buffa_descriptor::reflect::Reflectable for GetCSRFTokenResponse {
    /// Vtable-mode reflective handle: borrows `self` directly. No
    /// encode/decode round-trip and no allocation — the reflective
    /// accessors read this message's fields in place.
    #[inline]
    fn reflect(&self) -> ::buffa_descriptor::reflect::ReflectCow<'_> {
        ::buffa_descriptor::reflect::ReflectCow::Borrowed(self)
    }
}
impl ::buffa::MessageName for GetCSRFTokenResponse {
    const PACKAGE: &'static str = "auth.v2";
    const NAME: &'static str = "GetCSRFTokenResponse";
    const FULL_NAME: &'static str = "auth.v2.GetCSRFTokenResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/auth.v2.GetCSRFTokenResponse";
}
impl ::buffa::Message for GetCSRFTokenResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        size += self.__buffa_unknown_fields.encoded_len() as u64;
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        self.__buffa_unknown_fields.write_to(buf);
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            _ => {
                self.__buffa_unknown_fields
                    .push(::buffa::encoding::decode_unknown_field(tag, buf, ctx)?);
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.__buffa_unknown_fields.clear();
    }
}
impl ::buffa::ExtensionSet for GetCSRFTokenResponse {
    const PROTO_FQN: &'static str = "auth.v2.GetCSRFTokenResponse";
    fn unknown_fields(&self) -> &::buffa::UnknownFields {
        &self.__buffa_unknown_fields
    }
    fn unknown_fields_mut(&mut self) -> &mut ::buffa::UnknownFields {
        &mut self.__buffa_unknown_fields
    }
}
impl ::buffa::json_helpers::ProtoElemJson for GetCSRFTokenResponse {
    fn serialize_proto_json<S: ::serde::Serializer>(
        v: &Self,
        s: S,
    ) -> ::core::result::Result<S::Ok, S::Error> {
        ::serde::Serialize::serialize(v, s)
    }
    fn deserialize_proto_json<'de, D: ::serde::Deserializer<'de>>(
        d: D,
    ) -> ::core::result::Result<Self, D::Error> {
        <Self as ::serde::Deserialize>::deserialize(d)
    }
}
#[doc(hidden)]
pub const __GET_CSRF_TOKEN_RESPONSE_JSON_ANY: ::buffa::type_registry::JsonAnyEntry = ::buffa::type_registry::JsonAnyEntry {
    type_url: "type.googleapis.com/auth.v2.GetCSRFTokenResponse",
    to_json: ::buffa::type_registry::any_to_json::<GetCSRFTokenResponse>,
    from_json: ::buffa::type_registry::any_from_json::<GetCSRFTokenResponse>,
    is_wkt: false,
};
