#![allow(clippy::all, warnings)]
// This file is generated by global-rs/generate-permissions-checking. Do not edit manually.

pub fn get_route_from_public_url(url: &str) -> Option<&'static str> {
    match url {
        "/" | "/index.html" | "/auth.v2.AuthService/FrontendIndex" => return Some("/auth.v2.AuthService/FrontendIndex"),
"/auth.v2.AuthService/GetCSRFToken" => return Some("/auth.v2.AuthService/GetCSRFToken"),
"/auth.v2.AuthService/GetDevToken" => return Some("/auth.v2.AuthService/GetDevToken"),
"/auth.v2.AuthService/GetJWTPublicKey" => return Some("/auth.v2.AuthService/GetJWTPublicKey"),
"/auth.v2.AuthService/ListUsers" => return Some("/auth.v2.AuthService/ListUsers"),
"/auth.v2.AuthService/Login" => return Some("/auth.v2.AuthService/Login"),
"/auth.v2.AuthService/RenewJWT" => return Some("/auth.v2.AuthService/RenewJWT"),
_ => None,
    }
}


use std::collections::BTreeMap;
use hxi2_proto::proto::auth::v2::Permission;

#[derive(Debug, Clone)]
pub struct MethodPermissions {
    pub allow_roles: &'static [Permission],
    pub is_public: bool,
    pub public_url: Option<&'static [&'static str]>,
    pub compiled_permissions_bitfield: i64,
    pub csrf_token_header: Option<&'static str>,
    pub csrf_token_cookie: Option<&'static str>,
    pub response_cors_headers: Option<BTreeMap<&'static str, &'static str>>,
    pub enforce_csrf: bool,
}

pub trait MethodPermissionsOptionExt {
    fn check_permissions(&self, user_permissions: i64) -> bool;
}

impl MethodPermissionsOptionExt for MethodPermissions {
    fn check_permissions(&self, user_permissions: i64) -> bool {
        if self.is_public {
            return true;
        }
        (user_permissions & self.compiled_permissions_bitfield) > 0
    }
}

impl MethodPermissionsOptionExt for Option<&MethodPermissions> {
    fn check_permissions(&self, user_permissions: i64) -> bool {
        match self {
            Some(perm) => perm.check_permissions(user_permissions),
            None => false,
        }
    }
}

#[derive(Debug, Clone)]
pub struct CompiledPermissions {
    pub permissions: &'static [(&'static str, MethodPermissions)],
    pub hash: &'static str,
}

impl CompiledPermissions {
    pub fn get_by_route(&self, route: &str) -> Option<&MethodPermissions> {
        match route {
				"/auth.v2.AuthService/FrontendIndex" => return Some(&self.permissions[0].1),
				"/auth.v2.AuthService/GetCSRFToken" => return Some(&self.permissions[1].1),
				"/auth.v2.AuthService/GetDevToken" => return Some(&self.permissions[2].1),
				"/auth.v2.AuthService/GetJWTPublicKey" => return Some(&self.permissions[3].1),
				"/auth.v2.AuthService/ListUsers" => return Some(&self.permissions[4].1),
				"/auth.v2.AuthService/Login" => return Some(&self.permissions[5].1),
				"/auth.v2.AuthService/RenewJWT" => return Some(&self.permissions[6].1),
            _ => None,
        }
    }
}

pub fn get_compiled_permissions() -> &'static CompiledPermissions {
    static INSTANCE: CompiledPermissions = CompiledPermissions {
        permissions: &[
            ("/auth.v2.AuthService/FrontendIndex", MethodPermissions {
                allow_roles: &[
					Permission::PERMISSION_ADMIN,
                ],
                is_public: true,
                public_url: Some(&["/", "/index.html"]),
                compiled_permissions_bitfield: 2,
                csrf_token_header: Some("X-CSRF-Token"),
                csrf_token_cookie: Some("csrf_token"),
                response_cors_headers: None,
                enforce_csrf: false,
            }),
            ("/auth.v2.AuthService/GetCSRFToken", MethodPermissions {
                allow_roles: &[
					Permission::PERMISSION_ADMIN,
                ],
                is_public: true,
                public_url: None,
                compiled_permissions_bitfield: 2,
                csrf_token_header: Some("X-CSRF-Token"),
                csrf_token_cookie: Some("csrf_token"),
                response_cors_headers: None,
                enforce_csrf: false,
            }),
            ("/auth.v2.AuthService/GetDevToken", MethodPermissions {
                allow_roles: &[
					Permission::PERMISSION_ADMIN,
                ],
                is_public: true,
                public_url: None,
                compiled_permissions_bitfield: 2,
                csrf_token_header: Some("X-CSRF-Token"),
                csrf_token_cookie: Some("csrf_token"),
                response_cors_headers: None,
                enforce_csrf: false,
            }),
            ("/auth.v2.AuthService/GetJWTPublicKey", MethodPermissions {
                allow_roles: &[
					Permission::PERMISSION_ADMIN,
					Permission::PERMISSION_API_JWT,
                ],
                is_public: false,
                public_url: None,
                compiled_permissions_bitfield: 10,
                csrf_token_header: Some("X-CSRF-Token"),
                csrf_token_cookie: Some("csrf_token"),
                response_cors_headers: None,
                enforce_csrf: false,
            }),
            ("/auth.v2.AuthService/ListUsers", MethodPermissions {
                allow_roles: &[
					Permission::PERMISSION_ADMIN,
					Permission::PERMISSION_API_LIST_USERS,
                ],
                is_public: false,
                public_url: None,
                compiled_permissions_bitfield: 10,
                csrf_token_header: Some("X-CSRF-Token"),
                csrf_token_cookie: Some("csrf_token"),
                response_cors_headers: None,
                enforce_csrf: false,
            }),
            ("/auth.v2.AuthService/Login", MethodPermissions {
                allow_roles: &[
					Permission::PERMISSION_ADMIN,
                ],
                is_public: true,
                public_url: None,
                compiled_permissions_bitfield: 2,
                csrf_token_header: Some("X-CSRF-Token"),
                csrf_token_cookie: Some("csrf_token"),
                response_cors_headers: None,
                enforce_csrf: true,
            }),
            ("/auth.v2.AuthService/RenewJWT", MethodPermissions {
                allow_roles: &[
					Permission::PERMISSION_ADMIN,
					Permission::PERMISSION_API_JWT,
                ],
                is_public: false,
                public_url: None,
                compiled_permissions_bitfield: 10,
                csrf_token_header: Some("X-CSRF-Token"),
                csrf_token_cookie: Some("csrf_token"),
                response_cors_headers: None,
                enforce_csrf: false,
            }),
        ],
        hash: "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
    };

    &INSTANCE
}

pub fn get_by_route(route: &str) -> Option<&'static MethodPermissions> {
    get_compiled_permissions().get_by_route(route)
}
